//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:12 AM EET 
//


package com.izibiz.smm.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SMM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SMM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HEADER" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CUSTOMER" type="{http://schemas.i2i.com/ei/common}CUSTOMER"/&gt;
 *                   &lt;element name="ISSUE_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;element name="PAYABLE_AMOUNT" type="{http://schemas.i2i.com/ei/common}AmountType" minOccurs="0"/&gt;
 *                   &lt;element name="PROFILE_ID" type="{http://schemas.i2i.com/ei/wsdl}PROFILE_ID" minOccurs="0"/&gt;
 *                   &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="SMS_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="SMS_STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="EMAIL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="EMAIL_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="EMAIL_STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="FILENAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="HASH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CDATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                   &lt;element name="REPORT_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="REPORT_STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CANCEL_REPORT_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                   &lt;element name="NO_REPORT_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CONTENT" type="{http://www.w3.org/2005/05/xmlmime}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *       &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SMM", propOrder = {
    "header",
    "content"
})
public class SMM {

    @XmlElement(name = "HEADER")
    protected SMM.HEADER header;
    @XmlElement(name = "CONTENT")
    protected Base64Binary content;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String id;
    @XmlAttribute(name = "UUID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String uuid;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link SMM.HEADER }
     *     
     */
    public SMM.HEADER getHEADER() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link SMM.HEADER }
     *     
     */
    public void setHEADER(SMM.HEADER value) {
        this.header = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Base64Binary }
     *     
     */
    public Base64Binary getCONTENT() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64Binary }
     *     
     */
    public void setCONTENT(Base64Binary value) {
        this.content = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUUID(String value) {
        this.uuid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CUSTOMER" type="{http://schemas.i2i.com/ei/common}CUSTOMER"/&gt;
     *         &lt;element name="ISSUE_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;element name="PAYABLE_AMOUNT" type="{http://schemas.i2i.com/ei/common}AmountType" minOccurs="0"/&gt;
     *         &lt;element name="PROFILE_ID" type="{http://schemas.i2i.com/ei/wsdl}PROFILE_ID" minOccurs="0"/&gt;
     *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="SMS_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="SMS_STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="EMAIL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="EMAIL_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="EMAIL_STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="FILENAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="HASH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CDATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *         &lt;element name="REPORT_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="REPORT_STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CANCEL_REPORT_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *         &lt;element name="NO_REPORT_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customer",
        "issuedate",
        "payableamount",
        "profileid",
        "status",
        "statuscode",
        "statusdescription",
        "smsstatuscode",
        "smsstatusdescription",
        "email",
        "emailstatuscode",
        "emailstatusdescription",
        "filename",
        "hash",
        "cdate",
        "reportstatuscode",
        "reportstatusdescription",
        "cancelreportdate",
        "noreportdate"
    })
    public static class HEADER {

        @XmlElement(name = "CUSTOMER", required = true)
        protected CUSTOMER customer;
        @XmlElement(name = "ISSUE_DATE")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar issuedate;
        @XmlElement(name = "PAYABLE_AMOUNT")
        protected AmountType payableamount;
        @XmlElement(name = "PROFILE_ID")
        @XmlSchemaType(name = "token")
        protected PROFILEID profileid;
        @XmlElement(name = "STATUS")
        protected String status;
        @XmlElement(name = "STATUS_CODE")
        protected Integer statuscode;
        @XmlElement(name = "STATUS_DESCRIPTION")
        protected String statusdescription;
        @XmlElement(name = "SMS_STATUS_CODE")
        protected Integer smsstatuscode;
        @XmlElement(name = "SMS_STATUS_DESCRIPTION")
        protected String smsstatusdescription;
        @XmlElement(name = "EMAIL")
        protected List<String> email;
        @XmlElement(name = "EMAIL_STATUS_CODE")
        protected Integer emailstatuscode;
        @XmlElement(name = "EMAIL_STATUS_DESCRIPTION")
        protected String emailstatusdescription;
        @XmlElement(name = "FILENAME")
        protected String filename;
        @XmlElement(name = "HASH")
        protected String hash;
        @XmlElement(name = "CDATE")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar cdate;
        @XmlElement(name = "REPORT_STATUS_CODE")
        protected Integer reportstatuscode;
        @XmlElement(name = "REPORT_STATUS_DESCRIPTION")
        protected String reportstatusdescription;
        @XmlElement(name = "CANCEL_REPORT_DATE")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar cancelreportdate;
        @XmlElement(name = "NO_REPORT_DATE")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar noreportdate;

        /**
         * Gets the value of the customer property.
         * 
         * @return
         *     possible object is
         *     {@link CUSTOMER }
         *     
         */
        public CUSTOMER getCUSTOMER() {
            return customer;
        }

        /**
         * Sets the value of the customer property.
         * 
         * @param value
         *     allowed object is
         *     {@link CUSTOMER }
         *     
         */
        public void setCUSTOMER(CUSTOMER value) {
            this.customer = value;
        }

        /**
         * Gets the value of the issuedate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getISSUEDATE() {
            return issuedate;
        }

        /**
         * Sets the value of the issuedate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setISSUEDATE(XMLGregorianCalendar value) {
            this.issuedate = value;
        }

        /**
         * Gets the value of the payableamount property.
         * 
         * @return
         *     possible object is
         *     {@link AmountType }
         *     
         */
        public AmountType getPAYABLEAMOUNT() {
            return payableamount;
        }

        /**
         * Sets the value of the payableamount property.
         * 
         * @param value
         *     allowed object is
         *     {@link AmountType }
         *     
         */
        public void setPAYABLEAMOUNT(AmountType value) {
            this.payableamount = value;
        }

        /**
         * Gets the value of the profileid property.
         * 
         * @return
         *     possible object is
         *     {@link PROFILEID }
         *     
         */
        public PROFILEID getPROFILEID() {
            return profileid;
        }

        /**
         * Sets the value of the profileid property.
         * 
         * @param value
         *     allowed object is
         *     {@link PROFILEID }
         *     
         */
        public void setPROFILEID(PROFILEID value) {
            this.profileid = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTATUS() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTATUS(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the statuscode property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSTATUSCODE() {
            return statuscode;
        }

        /**
         * Sets the value of the statuscode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSTATUSCODE(Integer value) {
            this.statuscode = value;
        }

        /**
         * Gets the value of the statusdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTATUSDESCRIPTION() {
            return statusdescription;
        }

        /**
         * Sets the value of the statusdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTATUSDESCRIPTION(String value) {
            this.statusdescription = value;
        }

        /**
         * Gets the value of the smsstatuscode property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSMSSTATUSCODE() {
            return smsstatuscode;
        }

        /**
         * Sets the value of the smsstatuscode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSMSSTATUSCODE(Integer value) {
            this.smsstatuscode = value;
        }

        /**
         * Gets the value of the smsstatusdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSMSSTATUSDESCRIPTION() {
            return smsstatusdescription;
        }

        /**
         * Sets the value of the smsstatusdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSMSSTATUSDESCRIPTION(String value) {
            this.smsstatusdescription = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the email property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEMAIL().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEMAIL() {
            if (email == null) {
                email = new ArrayList<String>();
            }
            return this.email;
        }

        /**
         * Gets the value of the emailstatuscode property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getEMAILSTATUSCODE() {
            return emailstatuscode;
        }

        /**
         * Sets the value of the emailstatuscode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setEMAILSTATUSCODE(Integer value) {
            this.emailstatuscode = value;
        }

        /**
         * Gets the value of the emailstatusdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMAILSTATUSDESCRIPTION() {
            return emailstatusdescription;
        }

        /**
         * Sets the value of the emailstatusdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMAILSTATUSDESCRIPTION(String value) {
            this.emailstatusdescription = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFILENAME() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFILENAME(String value) {
            this.filename = value;
        }

        /**
         * Gets the value of the hash property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHASH() {
            return hash;
        }

        /**
         * Sets the value of the hash property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHASH(String value) {
            this.hash = value;
        }

        /**
         * Gets the value of the cdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCDATE() {
            return cdate;
        }

        /**
         * Sets the value of the cdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCDATE(XMLGregorianCalendar value) {
            this.cdate = value;
        }

        /**
         * Gets the value of the reportstatuscode property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getREPORTSTATUSCODE() {
            return reportstatuscode;
        }

        /**
         * Sets the value of the reportstatuscode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setREPORTSTATUSCODE(Integer value) {
            this.reportstatuscode = value;
        }

        /**
         * Gets the value of the reportstatusdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREPORTSTATUSDESCRIPTION() {
            return reportstatusdescription;
        }

        /**
         * Sets the value of the reportstatusdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREPORTSTATUSDESCRIPTION(String value) {
            this.reportstatusdescription = value;
        }

        /**
         * Gets the value of the cancelreportdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCANCELREPORTDATE() {
            return cancelreportdate;
        }

        /**
         * Sets the value of the cancelreportdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCANCELREPORTDATE(XMLGregorianCalendar value) {
            this.cancelreportdate = value;
        }

        /**
         * Gets the value of the noreportdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getNOREPORTDATE() {
            return noreportdate;
        }

        /**
         * Sets the value of the noreportdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setNOREPORTDATE(XMLGregorianCalendar value) {
            this.noreportdate = value;
        }

    }

}
