//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:12 AM EET 
//


package com.izibiz.irsaliye.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SIGNTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SIGNTYPE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HSM_CUSTOMER"/&gt;
 *     &lt;enumeration value="HSM_ENTEGRATOR"/&gt;
 *     &lt;enumeration value="HSM_CLIENT_SIGNED"/&gt;
 *     &lt;enumeration value="TOKEN_CUSTOMER"/&gt;
 *     &lt;enumeration value="TOKEN_ENTEGRATOR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SIGNTYPE")
@XmlEnum
public enum SIGNTYPE {

    HSM_CUSTOMER,
    HSM_ENTEGRATOR,
    HSM_CLIENT_SIGNED,
    TOKEN_CUSTOMER,
    TOKEN_ENTEGRATOR;

    public String value() {
        return name();
    }

    public static SIGNTYPE fromValue(String v) {
        return valueOf(v);
    }

}
