//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:09 AM EET 
//


package com.izibiz.auth.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetUserAuthorizationResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetUserAuthorizationResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AUTHORIZED" type="{http://schemas.i2i.com/ei/wsdl}AUTHORIZED" minOccurs="0"/&gt;
 *         &lt;element name="ERROR_TYPE" type="{http://schemas.i2i.com/ei/entity}REQUEST_ERRORType" minOccurs="0"/&gt;
 *         &lt;element name="PRODUCT_LIST" type="{http://schemas.i2i.com/ei/wsdl}PRODUCT_LIST" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUserAuthorizationResponse", propOrder = {
    "authorized",
    "errortype",
    "productlist"
})
public class GetUserAuthorizationResponse {

    @XmlElement(name = "AUTHORIZED")
    @XmlSchemaType(name = "token")
    protected AUTHORIZED authorized;
    @XmlElement(name = "ERROR_TYPE")
    protected REQUESTERRORType errortype;
    @XmlElement(name = "PRODUCT_LIST")
    protected PRODUCTLIST productlist;

    /**
     * Gets the value of the authorized property.
     * 
     * @return
     *     possible object is
     *     {@link AUTHORIZED }
     *     
     */
    public AUTHORIZED getAUTHORIZED() {
        return authorized;
    }

    /**
     * Sets the value of the authorized property.
     * 
     * @param value
     *     allowed object is
     *     {@link AUTHORIZED }
     *     
     */
    public void setAUTHORIZED(AUTHORIZED value) {
        this.authorized = value;
    }

    /**
     * Gets the value of the errortype property.
     * 
     * @return
     *     possible object is
     *     {@link REQUESTERRORType }
     *     
     */
    public REQUESTERRORType getERRORTYPE() {
        return errortype;
    }

    /**
     * Sets the value of the errortype property.
     * 
     * @param value
     *     allowed object is
     *     {@link REQUESTERRORType }
     *     
     */
    public void setERRORTYPE(REQUESTERRORType value) {
        this.errortype = value;
    }

    /**
     * Gets the value of the productlist property.
     * 
     * @return
     *     possible object is
     *     {@link PRODUCTLIST }
     *     
     */
    public PRODUCTLIST getPRODUCTLIST() {
        return productlist;
    }

    /**
     * Sets the value of the productlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRODUCTLIST }
     *     
     */
    public void setPRODUCTLIST(PRODUCTLIST value) {
        this.productlist = value;
    }

}
