//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:09 AM EET 
//


package com.izibiz.auth.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Request response related context information
 * 				including data such as RETURN_CODE, DETAILED_RESULT
 * 				information etc.
 * 			
 * 
 * <p>Java class for REQUEST_RETURNType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REQUEST_RETURNType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="INTL_TXN_ID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="CLIENT_TXN_ID" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="RETURN_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="WARNINGS" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REQUEST_RETURNType", namespace = "http://schemas.i2i.com/ei/entity", propOrder = {
    "intltxnid",
    "clienttxnid",
    "returncode",
    "warnings"
})
public class REQUESTRETURNType {

    @XmlElement(name = "INTL_TXN_ID")
    protected long intltxnid;
    @XmlElement(name = "CLIENT_TXN_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String clienttxnid;
    @XmlElement(name = "RETURN_CODE")
    protected int returncode;
    @XmlElement(name = "WARNINGS")
    protected List<String> warnings;

    /**
     * Gets the value of the intltxnid property.
     * 
     */
    public long getINTLTXNID() {
        return intltxnid;
    }

    /**
     * Sets the value of the intltxnid property.
     * 
     */
    public void setINTLTXNID(long value) {
        this.intltxnid = value;
    }

    /**
     * Gets the value of the clienttxnid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLIENTTXNID() {
        return clienttxnid;
    }

    /**
     * Sets the value of the clienttxnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLIENTTXNID(String value) {
        this.clienttxnid = value;
    }

    /**
     * Gets the value of the returncode property.
     * 
     */
    public int getRETURNCODE() {
        return returncode;
    }

    /**
     * Sets the value of the returncode property.
     * 
     */
    public void setRETURNCODE(int value) {
        this.returncode = value;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warnings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWARNINGS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWARNINGS() {
        if (warnings == null) {
            warnings = new ArrayList<String>();
        }
        return this.warnings;
    }

}
