//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:09 AM EET 
//


package com.izibiz.oib.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GetInvoiceCountRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetInvoiceCountRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.i2i.com/ei/entity}REQUEST"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ISSUE_DATE_START" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ISSUE_DATE_END" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="CDATE_START" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="CDATE_END" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="DIRECTION" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetInvoiceCountRequest", propOrder = {
    "issuedatestart",
    "issuedateend",
    "cdatestart",
    "cdateend",
    "direction"
})
public class GetInvoiceCountRequest
    extends REQUEST
{

    @XmlElement(name = "ISSUE_DATE_START")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issuedatestart;
    @XmlElement(name = "ISSUE_DATE_END")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issuedateend;
    @XmlElement(name = "CDATE_START")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cdatestart;
    @XmlElement(name = "CDATE_END")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cdateend;
    @XmlElement(name = "DIRECTION")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String direction;

    /**
     * Gets the value of the issuedatestart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getISSUEDATESTART() {
        return issuedatestart;
    }

    /**
     * Sets the value of the issuedatestart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setISSUEDATESTART(XMLGregorianCalendar value) {
        this.issuedatestart = value;
    }

    /**
     * Gets the value of the issuedateend property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getISSUEDATEEND() {
        return issuedateend;
    }

    /**
     * Sets the value of the issuedateend property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setISSUEDATEEND(XMLGregorianCalendar value) {
        this.issuedateend = value;
    }

    /**
     * Gets the value of the cdatestart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCDATESTART() {
        return cdatestart;
    }

    /**
     * Sets the value of the cdatestart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCDATESTART(XMLGregorianCalendar value) {
        this.cdatestart = value;
    }

    /**
     * Gets the value of the cdateend property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCDATEEND() {
        return cdateend;
    }

    /**
     * Sets the value of the cdateend property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCDATEEND(XMLGregorianCalendar value) {
        this.cdateend = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIRECTION() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIRECTION(String value) {
        this.direction = value;
    }

}
