//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:09 AM EET 
//


package com.izibiz.oib.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for INVOICE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INVOICE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="HEADER" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SENDER" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                   &lt;element name="RECEIVER" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                   &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CUSTOMER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ISSUE_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;element name="PAYABLE_AMOUNT" type="{http://schemas.i2i.com/ei/common}AmountType" minOccurs="0"/&gt;
 *                   &lt;element name="FROM" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                   &lt;element name="TO" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                   &lt;element name="PROFILEID" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                   &lt;element name="INVOICE_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="GIB_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="GIB_STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="RESPONSE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="RESPONSE_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="FILENAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="HASH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CDATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                   &lt;element name="ENVELOPE_IDENTIFIER" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CONTENT" type="{http://www.w3.org/2005/05/xmlmime}base64Binary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *       &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}token" /&gt;
 *       &lt;attribute name="LIST_ID" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INVOICE", propOrder = {
    "header",
    "content"
})
@XmlSeeAlso({
    com.izibiz.oib.ws.GetInvoiceStatusResponse.INVOICESTATUS.class
})
public class INVOICE {

    @XmlElement(name = "HEADER")
    protected INVOICE.HEADER header;
    @XmlElement(name = "CONTENT")
    protected Base64Binary content;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String id;
    @XmlAttribute(name = "UUID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String uuid;
    @XmlAttribute(name = "LIST_ID")
    protected Integer listid;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link INVOICE.HEADER }
     *     
     */
    public INVOICE.HEADER getHEADER() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link INVOICE.HEADER }
     *     
     */
    public void setHEADER(INVOICE.HEADER value) {
        this.header = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Base64Binary }
     *     
     */
    public Base64Binary getCONTENT() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64Binary }
     *     
     */
    public void setCONTENT(Base64Binary value) {
        this.content = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUUID(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the listid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLISTID() {
        return listid;
    }

    /**
     * Sets the value of the listid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLISTID(Integer value) {
        this.listid = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SENDER" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *         &lt;element name="RECEIVER" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *         &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CUSTOMER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ISSUE_DATE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;element name="PAYABLE_AMOUNT" type="{http://schemas.i2i.com/ei/common}AmountType" minOccurs="0"/&gt;
     *         &lt;element name="FROM" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *         &lt;element name="TO" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *         &lt;element name="PROFILEID" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *         &lt;element name="INVOICE_TYPE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="GIB_STATUS_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="GIB_STATUS_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="RESPONSE_CODE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="RESPONSE_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="FILENAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="HASH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CDATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *         &lt;element name="ENVELOPE_IDENTIFIER" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sender",
        "receiver",
        "supplier",
        "customer",
        "issuedate",
        "payableamount",
        "from",
        "to",
        "profileid",
        "invoicetypecode",
        "status",
        "statusdescription",
        "gibstatuscode",
        "gibstatusdescription",
        "responsecode",
        "responsedescription",
        "filename",
        "hash",
        "cdate",
        "envelopeidentifier"
    })
    public static class HEADER {

        @XmlElement(name = "SENDER")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String sender;
        @XmlElement(name = "RECEIVER")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String receiver;
        @XmlElement(name = "SUPPLIER")
        protected String supplier;
        @XmlElement(name = "CUSTOMER")
        protected String customer;
        @XmlElement(name = "ISSUE_DATE")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar issuedate;
        @XmlElement(name = "PAYABLE_AMOUNT")
        protected AmountType payableamount;
        @XmlElement(name = "FROM")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String from;
        @XmlElement(name = "TO")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String to;
        @XmlElement(name = "PROFILEID")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String profileid;
        @XmlElement(name = "INVOICE_TYPE_CODE")
        protected String invoicetypecode;
        @XmlElement(name = "STATUS")
        protected String status;
        @XmlElement(name = "STATUS_DESCRIPTION")
        protected String statusdescription;
        @XmlElement(name = "GIB_STATUS_CODE")
        protected Integer gibstatuscode;
        @XmlElement(name = "GIB_STATUS_DESCRIPTION")
        protected String gibstatusdescription;
        @XmlElement(name = "RESPONSE_CODE")
        protected String responsecode;
        @XmlElement(name = "RESPONSE_DESCRIPTION")
        protected String responsedescription;
        @XmlElement(name = "FILENAME")
        protected String filename;
        @XmlElement(name = "HASH")
        protected String hash;
        @XmlElement(name = "CDATE")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar cdate;
        @XmlElement(name = "ENVELOPE_IDENTIFIER")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String envelopeidentifier;

        /**
         * Gets the value of the sender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSENDER() {
            return sender;
        }

        /**
         * Sets the value of the sender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSENDER(String value) {
            this.sender = value;
        }

        /**
         * Gets the value of the receiver property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRECEIVER() {
            return receiver;
        }

        /**
         * Sets the value of the receiver property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRECEIVER(String value) {
            this.receiver = value;
        }

        /**
         * Gets the value of the supplier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSUPPLIER() {
            return supplier;
        }

        /**
         * Sets the value of the supplier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSUPPLIER(String value) {
            this.supplier = value;
        }

        /**
         * Gets the value of the customer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCUSTOMER() {
            return customer;
        }

        /**
         * Sets the value of the customer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCUSTOMER(String value) {
            this.customer = value;
        }

        /**
         * Gets the value of the issuedate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getISSUEDATE() {
            return issuedate;
        }

        /**
         * Sets the value of the issuedate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setISSUEDATE(XMLGregorianCalendar value) {
            this.issuedate = value;
        }

        /**
         * Gets the value of the payableamount property.
         * 
         * @return
         *     possible object is
         *     {@link AmountType }
         *     
         */
        public AmountType getPAYABLEAMOUNT() {
            return payableamount;
        }

        /**
         * Sets the value of the payableamount property.
         * 
         * @param value
         *     allowed object is
         *     {@link AmountType }
         *     
         */
        public void setPAYABLEAMOUNT(AmountType value) {
            this.payableamount = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFROM() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFROM(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTO() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTO(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the profileid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPROFILEID() {
            return profileid;
        }

        /**
         * Sets the value of the profileid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPROFILEID(String value) {
            this.profileid = value;
        }

        /**
         * Gets the value of the invoicetypecode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINVOICETYPECODE() {
            return invoicetypecode;
        }

        /**
         * Sets the value of the invoicetypecode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINVOICETYPECODE(String value) {
            this.invoicetypecode = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTATUS() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTATUS(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the statusdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTATUSDESCRIPTION() {
            return statusdescription;
        }

        /**
         * Sets the value of the statusdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTATUSDESCRIPTION(String value) {
            this.statusdescription = value;
        }

        /**
         * Gets the value of the gibstatuscode property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getGIBSTATUSCODE() {
            return gibstatuscode;
        }

        /**
         * Sets the value of the gibstatuscode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setGIBSTATUSCODE(Integer value) {
            this.gibstatuscode = value;
        }

        /**
         * Gets the value of the gibstatusdescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGIBSTATUSDESCRIPTION() {
            return gibstatusdescription;
        }

        /**
         * Sets the value of the gibstatusdescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGIBSTATUSDESCRIPTION(String value) {
            this.gibstatusdescription = value;
        }

        /**
         * Gets the value of the responsecode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRESPONSECODE() {
            return responsecode;
        }

        /**
         * Sets the value of the responsecode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRESPONSECODE(String value) {
            this.responsecode = value;
        }

        /**
         * Gets the value of the responsedescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRESPONSEDESCRIPTION() {
            return responsedescription;
        }

        /**
         * Sets the value of the responsedescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRESPONSEDESCRIPTION(String value) {
            this.responsedescription = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFILENAME() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFILENAME(String value) {
            this.filename = value;
        }

        /**
         * Gets the value of the hash property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHASH() {
            return hash;
        }

        /**
         * Sets the value of the hash property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHASH(String value) {
            this.hash = value;
        }

        /**
         * Gets the value of the cdate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCDATE() {
            return cdate;
        }

        /**
         * Sets the value of the cdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCDATE(XMLGregorianCalendar value) {
            this.cdate = value;
        }

        /**
         * Gets the value of the envelopeidentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getENVELOPEIDENTIFIER() {
            return envelopeidentifier;
        }

        /**
         * Sets the value of the envelopeidentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setENVELOPEIDENTIFIER(String value) {
            this.envelopeidentifier = value;
        }

    }

}
