//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:09 AM EET 
//


package com.izibiz.oib.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.izibiz.oib.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestFault_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "RequestFault");
    private final static QName _LoginRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "LoginRequest");
    private final static QName _LoginResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "LoginResponse");
    private final static QName _LogoutRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "LogoutRequest");
    private final static QName _LogoutResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "LogoutResponse");
    private final static QName _PrepareProcessUserRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "PrepareProcessUserRequest");
    private final static QName _PrepareProcessUserResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "PrepareProcessUserResponse");
    private final static QName _PrepareCancelUserRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "PrepareCancelUserRequest");
    private final static QName _PrepareCancelUserResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "PrepareCancelUserResponse");
    private final static QName _ProcessUserRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "ProcessUserRequest");
    private final static QName _ProcessUserResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "ProcessUserResponse");
    private final static QName _CancelUserRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "CancelUserRequest");
    private final static QName _CancelUserResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "CancelUserResponse");
    private final static QName _SendInvoiceRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "SendInvoiceRequest");
    private final static QName _SendInvoiceResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "SendInvoiceResponse");
    private final static QName _GetInvoiceRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceRequest");
    private final static QName _GetInvoiceResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceResponse");
    private final static QName _MarkInvoiceRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "MarkInvoiceRequest");
    private final static QName _MarkInvoiceResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "MarkInvoiceResponse");
    private final static QName _PrepareInvoiceResponseRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "PrepareInvoiceResponseRequest");
    private final static QName _PrepareInvoiceResponseResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "PrepareInvoiceResponseResponse");
    private final static QName _SendInvoiceResponseRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "SendInvoiceResponseRequest");
    private final static QName _SendInvoiceResponseResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "SendInvoiceResponseResponse");
    private final static QName _SendInvoiceResponseWithServerSignRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "SendInvoiceResponseWithServerSignRequest");
    private final static QName _SendInvoiceResponseWithServerSignResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "SendInvoiceResponseWithServerSignResponse");
    private final static QName _GetUserListRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetUserListRequest");
    private final static QName _GetUserListResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetUserListResponse");
    private final static QName _GetUserListBinaryRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetUserListBinaryRequest");
    private final static QName _GetUserListBinaryResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetUserListBinaryResponse");
    private final static QName _CheckUserRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "CheckUserRequest");
    private final static QName _CheckUserResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "CheckUserResponse");
    private final static QName _GetInvoiceStatusRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceStatusRequest");
    private final static QName _GetInvoiceStatusResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceStatusResponse");
    private final static QName _GetInvoiceStatusAllRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceStatusAllRequest");
    private final static QName _GetInvoiceStatusAllResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceStatusAllResponse");
    private final static QName _CancelDraftInvoiceRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "CancelDraftInvoiceRequest");
    private final static QName _CancelDraftInvoiceResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "CancelDraftInvoiceResponse");
    private final static QName _LoadInvoiceRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "LoadInvoiceRequest");
    private final static QName _LoadInvoiceResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "LoadInvoiceResponse");
    private final static QName _GetEnvelopeRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetEnvelopeRequest");
    private final static QName _GetEnvelopeResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetEnvelopeResponse");
    private final static QName _MarkEnvelopeRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "MarkEnvelopeRequest");
    private final static QName _MarkEnvelopeResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "MarkEnvelopeResponse");
    private final static QName _GetEnvelopeStatusRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetEnvelopeStatusRequest");
    private final static QName _GetEnvelopeStatusResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetEnvelopeStatusResponse");
    private final static QName _GetInvoiceWithTypeRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceWithTypeRequest");
    private final static QName _GetInvoiceWithTypeResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceWithTypeResponse");
    private final static QName _GetInvoiceCountRequest_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceCountRequest");
    private final static QName _GetInvoiceCountResponse_QNAME = new QName("http://schemas.i2i.com/ei/wsdl", "GetInvoiceCountResponse");
    private final static QName _GetAppRespRequest_QNAME = new QName("http://gib.gov.tr/vedop3/eFatura", "getAppRespRequest");
    private final static QName _GetAppRespResponse_QNAME = new QName("http://gib.gov.tr/vedop3/eFatura", "getAppRespResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.izibiz.oib.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.izibiz.oib.ws.ENVELOPE }
     * 
     */
    public com.izibiz.oib.ws.ENVELOPE createENVELOPE() {
        return new com.izibiz.oib.ws.ENVELOPE();
    }

    /**
     * Create an instance of {@link INVOICE }
     * 
     */
    public INVOICE createINVOICE() {
        return new INVOICE();
    }

    /**
     * Create an instance of {@link GetInvoiceWithTypeRequest }
     * 
     */
    public GetInvoiceWithTypeRequest createGetInvoiceWithTypeRequest() {
        return new GetInvoiceWithTypeRequest();
    }

    /**
     * Create an instance of {@link GetEnvelopeStatusRequest }
     * 
     */
    public GetEnvelopeStatusRequest createGetEnvelopeStatusRequest() {
        return new GetEnvelopeStatusRequest();
    }

    /**
     * Create an instance of {@link MarkEnvelopeRequest }
     * 
     */
    public MarkEnvelopeRequest createMarkEnvelopeRequest() {
        return new MarkEnvelopeRequest();
    }

    /**
     * Create an instance of {@link MarkEnvelopeRequest.MARK }
     * 
     */
    public MarkEnvelopeRequest.MARK createMarkEnvelopeRequestMARK() {
        return new MarkEnvelopeRequest.MARK();
    }

    /**
     * Create an instance of {@link GetEnvelopeRequest }
     * 
     */
    public GetEnvelopeRequest createGetEnvelopeRequest() {
        return new GetEnvelopeRequest();
    }

    /**
     * Create an instance of {@link GetEnvelopeRequest.ENVELOPESEARCHKEY }
     * 
     */
    public GetEnvelopeRequest.ENVELOPESEARCHKEY createGetEnvelopeRequestENVELOPESEARCHKEY() {
        return new GetEnvelopeRequest.ENVELOPESEARCHKEY();
    }

    /**
     * Create an instance of {@link GetInvoiceStatusResponse }
     * 
     */
    public GetInvoiceStatusResponse createGetInvoiceStatusResponse() {
        return new GetInvoiceStatusResponse();
    }

    /**
     * Create an instance of {@link MarkInvoiceRequest }
     * 
     */
    public MarkInvoiceRequest createMarkInvoiceRequest() {
        return new MarkInvoiceRequest();
    }

    /**
     * Create an instance of {@link GetInvoiceRequest }
     * 
     */
    public GetInvoiceRequest createGetInvoiceRequest() {
        return new GetInvoiceRequest();
    }

    /**
     * Create an instance of {@link SendInvoiceRequest }
     * 
     */
    public SendInvoiceRequest createSendInvoiceRequest() {
        return new SendInvoiceRequest();
    }

    /**
     * Create an instance of {@link REQUESTERRORType }
     * 
     */
    public REQUESTERRORType createREQUESTERRORType() {
        return new REQUESTERRORType();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link UserRequest }
     * 
     */
    public UserRequest createUserRequest() {
        return new UserRequest();
    }

    /**
     * Create an instance of {@link UserResponse }
     * 
     */
    public UserResponse createUserResponse() {
        return new UserResponse();
    }

    /**
     * Create an instance of {@link REQUESTRETURNType }
     * 
     */
    public REQUESTRETURNType createREQUESTRETURNType() {
        return new REQUESTRETURNType();
    }

    /**
     * Create an instance of {@link SendInvoiceResponse }
     * 
     */
    public SendInvoiceResponse createSendInvoiceResponse() {
        return new SendInvoiceResponse();
    }

    /**
     * Create an instance of {@link GetInvoiceResponse }
     * 
     */
    public GetInvoiceResponse createGetInvoiceResponse() {
        return new GetInvoiceResponse();
    }

    /**
     * Create an instance of {@link MarkInvoiceResponse }
     * 
     */
    public MarkInvoiceResponse createMarkInvoiceResponse() {
        return new MarkInvoiceResponse();
    }

    /**
     * Create an instance of {@link PrepareInvoiceResponseRequest }
     * 
     */
    public PrepareInvoiceResponseRequest createPrepareInvoiceResponseRequest() {
        return new PrepareInvoiceResponseRequest();
    }

    /**
     * Create an instance of {@link PrepareInvoiceResponseResponse }
     * 
     */
    public PrepareInvoiceResponseResponse createPrepareInvoiceResponseResponse() {
        return new PrepareInvoiceResponseResponse();
    }

    /**
     * Create an instance of {@link SendInvoiceResponseRequest }
     * 
     */
    public SendInvoiceResponseRequest createSendInvoiceResponseRequest() {
        return new SendInvoiceResponseRequest();
    }

    /**
     * Create an instance of {@link SendInvoiceResponseResponse }
     * 
     */
    public SendInvoiceResponseResponse createSendInvoiceResponseResponse() {
        return new SendInvoiceResponseResponse();
    }

    /**
     * Create an instance of {@link SendInvoiceResponseWithServerSignRequest }
     * 
     */
    public SendInvoiceResponseWithServerSignRequest createSendInvoiceResponseWithServerSignRequest() {
        return new SendInvoiceResponseWithServerSignRequest();
    }

    /**
     * Create an instance of {@link SendInvoiceResponseWithServerSignResponse }
     * 
     */
    public SendInvoiceResponseWithServerSignResponse createSendInvoiceResponseWithServerSignResponse() {
        return new SendInvoiceResponseWithServerSignResponse();
    }

    /**
     * Create an instance of {@link GetUserListRequest }
     * 
     */
    public GetUserListRequest createGetUserListRequest() {
        return new GetUserListRequest();
    }

    /**
     * Create an instance of {@link GetUserListResponse }
     * 
     */
    public GetUserListResponse createGetUserListResponse() {
        return new GetUserListResponse();
    }

    /**
     * Create an instance of {@link GetUserListBinaryRequest }
     * 
     */
    public GetUserListBinaryRequest createGetUserListBinaryRequest() {
        return new GetUserListBinaryRequest();
    }

    /**
     * Create an instance of {@link GetUserListBinaryResponse }
     * 
     */
    public GetUserListBinaryResponse createGetUserListBinaryResponse() {
        return new GetUserListBinaryResponse();
    }

    /**
     * Create an instance of {@link CheckUserRequest }
     * 
     */
    public CheckUserRequest createCheckUserRequest() {
        return new CheckUserRequest();
    }

    /**
     * Create an instance of {@link CheckUserResponse }
     * 
     */
    public CheckUserResponse createCheckUserResponse() {
        return new CheckUserResponse();
    }

    /**
     * Create an instance of {@link GetInvoiceStatusRequest }
     * 
     */
    public GetInvoiceStatusRequest createGetInvoiceStatusRequest() {
        return new GetInvoiceStatusRequest();
    }

    /**
     * Create an instance of {@link GetInvoiceStatusAllRequest }
     * 
     */
    public GetInvoiceStatusAllRequest createGetInvoiceStatusAllRequest() {
        return new GetInvoiceStatusAllRequest();
    }

    /**
     * Create an instance of {@link GetInvoiceStatusAllResponse }
     * 
     */
    public GetInvoiceStatusAllResponse createGetInvoiceStatusAllResponse() {
        return new GetInvoiceStatusAllResponse();
    }

    /**
     * Create an instance of {@link CancelDraftInvoiceRequest }
     * 
     */
    public CancelDraftInvoiceRequest createCancelDraftInvoiceRequest() {
        return new CancelDraftInvoiceRequest();
    }

    /**
     * Create an instance of {@link CancelDraftInvoiceResponse }
     * 
     */
    public CancelDraftInvoiceResponse createCancelDraftInvoiceResponse() {
        return new CancelDraftInvoiceResponse();
    }

    /**
     * Create an instance of {@link LoadInvoiceRequest }
     * 
     */
    public LoadInvoiceRequest createLoadInvoiceRequest() {
        return new LoadInvoiceRequest();
    }

    /**
     * Create an instance of {@link LoadInvoiceResponse }
     * 
     */
    public LoadInvoiceResponse createLoadInvoiceResponse() {
        return new LoadInvoiceResponse();
    }

    /**
     * Create an instance of {@link GetEnvelopeResponse }
     * 
     */
    public GetEnvelopeResponse createGetEnvelopeResponse() {
        return new GetEnvelopeResponse();
    }

    /**
     * Create an instance of {@link MarkEnvelopeResponse }
     * 
     */
    public MarkEnvelopeResponse createMarkEnvelopeResponse() {
        return new MarkEnvelopeResponse();
    }

    /**
     * Create an instance of {@link GetEnvelopeStatusResponse }
     * 
     */
    public GetEnvelopeStatusResponse createGetEnvelopeStatusResponse() {
        return new GetEnvelopeStatusResponse();
    }

    /**
     * Create an instance of {@link GetInvoiceWithTypeResponse }
     * 
     */
    public GetInvoiceWithTypeResponse createGetInvoiceWithTypeResponse() {
        return new GetInvoiceWithTypeResponse();
    }

    /**
     * Create an instance of {@link GetInvoiceCountRequest }
     * 
     */
    public GetInvoiceCountRequest createGetInvoiceCountRequest() {
        return new GetInvoiceCountRequest();
    }

    /**
     * Create an instance of {@link GetInvoiceCountResponse }
     * 
     */
    public GetInvoiceCountResponse createGetInvoiceCountResponse() {
        return new GetInvoiceCountResponse();
    }

    /**
     * Create an instance of {@link USERCONTENT }
     * 
     */
    public USERCONTENT createUSERCONTENT() {
        return new USERCONTENT();
    }

    /**
     * Create an instance of {@link GIBUSER }
     * 
     */
    public GIBUSER createGIBUSER() {
        return new GIBUSER();
    }

    /**
     * Create an instance of {@link CHANGEINFOType }
     * 
     */
    public CHANGEINFOType createCHANGEINFOType() {
        return new CHANGEINFOType();
    }

    /**
     * Create an instance of {@link LOVVALUEType }
     * 
     */
    public LOVVALUEType createLOVVALUEType() {
        return new LOVVALUEType();
    }

    /**
     * Create an instance of {@link ATTRIBUTESTYPE }
     * 
     */
    public ATTRIBUTESTYPE createATTRIBUTESTYPE() {
        return new ATTRIBUTESTYPE();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link REQUEST }
     * 
     */
    public REQUEST createREQUEST() {
        return new REQUEST();
    }

    /**
     * Create an instance of {@link REQUESTHEADERType }
     * 
     */
    public REQUESTHEADERType createREQUESTHEADERType() {
        return new REQUESTHEADERType();
    }

    /**
     * Create an instance of {@link REQUESTINFOType }
     * 
     */
    public REQUESTINFOType createREQUESTINFOType() {
        return new REQUESTINFOType();
    }

    /**
     * Create an instance of {@link Base64Binary }
     * 
     */
    public Base64Binary createBase64Binary() {
        return new Base64Binary();
    }

    /**
     * Create an instance of {@link HexBinary }
     * 
     */
    public HexBinary createHexBinary() {
        return new HexBinary();
    }

    /**
     * Create an instance of {@link GetAppRespRequestType }
     * 
     */
    public GetAppRespRequestType createGetAppRespRequestType() {
        return new GetAppRespRequestType();
    }

    /**
     * Create an instance of {@link GetAppRespResponseType }
     * 
     */
    public GetAppRespResponseType createGetAppRespResponseType() {
        return new GetAppRespResponseType();
    }

    /**
     * Create an instance of {@link com.izibiz.oib.ws.ENVELOPE.HEADER }
     * 
     */
    public com.izibiz.oib.ws.ENVELOPE.HEADER createENVELOPEHEADER() {
        return new com.izibiz.oib.ws.ENVELOPE.HEADER();
    }

    /**
     * Create an instance of {@link INVOICE.HEADER }
     * 
     */
    public INVOICE.HEADER createINVOICEHEADER() {
        return new INVOICE.HEADER();
    }

    /**
     * Create an instance of {@link GetInvoiceWithTypeRequest.INVOICESEARCHKEY }
     * 
     */
    public GetInvoiceWithTypeRequest.INVOICESEARCHKEY createGetInvoiceWithTypeRequestINVOICESEARCHKEY() {
        return new GetInvoiceWithTypeRequest.INVOICESEARCHKEY();
    }

    /**
     * Create an instance of {@link GetEnvelopeStatusRequest.ENVELOPE }
     * 
     */
    public GetEnvelopeStatusRequest.ENVELOPE createGetEnvelopeStatusRequestENVELOPE() {
        return new GetEnvelopeStatusRequest.ENVELOPE();
    }

    /**
     * Create an instance of {@link MarkEnvelopeRequest.MARK.ENVELOPE }
     * 
     */
    public MarkEnvelopeRequest.MARK.ENVELOPE createMarkEnvelopeRequestMARKENVELOPE() {
        return new MarkEnvelopeRequest.MARK.ENVELOPE();
    }

    /**
     * Create an instance of {@link GetEnvelopeRequest.ENVELOPESEARCHKEY.ELEMENT }
     * 
     */
    public GetEnvelopeRequest.ENVELOPESEARCHKEY.ELEMENT createGetEnvelopeRequestENVELOPESEARCHKEYELEMENT() {
        return new GetEnvelopeRequest.ENVELOPESEARCHKEY.ELEMENT();
    }

    /**
     * Create an instance of {@link GetInvoiceStatusResponse.INVOICESTATUS }
     * 
     */
    public GetInvoiceStatusResponse.INVOICESTATUS createGetInvoiceStatusResponseINVOICESTATUS() {
        return new GetInvoiceStatusResponse.INVOICESTATUS();
    }

    /**
     * Create an instance of {@link MarkInvoiceRequest.MARK }
     * 
     */
    public MarkInvoiceRequest.MARK createMarkInvoiceRequestMARK() {
        return new MarkInvoiceRequest.MARK();
    }

    /**
     * Create an instance of {@link GetInvoiceRequest.INVOICESEARCHKEY }
     * 
     */
    public GetInvoiceRequest.INVOICESEARCHKEY createGetInvoiceRequestINVOICESEARCHKEY() {
        return new GetInvoiceRequest.INVOICESEARCHKEY();
    }

    /**
     * Create an instance of {@link SendInvoiceRequest.SENDER }
     * 
     */
    public SendInvoiceRequest.SENDER createSendInvoiceRequestSENDER() {
        return new SendInvoiceRequest.SENDER();
    }

    /**
     * Create an instance of {@link SendInvoiceRequest.RECEIVER }
     * 
     */
    public SendInvoiceRequest.RECEIVER createSendInvoiceRequestRECEIVER() {
        return new SendInvoiceRequest.RECEIVER();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REQUESTERRORType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "RequestFault")
    public JAXBElement<REQUESTERRORType> createRequestFault(REQUESTERRORType value) {
        return new JAXBElement<REQUESTERRORType>(_RequestFault_QNAME, REQUESTERRORType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "LoginRequest")
    public JAXBElement<LoginRequest> createLoginRequest(LoginRequest value) {
        return new JAXBElement<LoginRequest>(_LoginRequest_QNAME, LoginRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "LoginResponse")
    public JAXBElement<LoginResponse> createLoginResponse(LoginResponse value) {
        return new JAXBElement<LoginResponse>(_LoginResponse_QNAME, LoginResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoutRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "LogoutRequest")
    public JAXBElement<LogoutRequest> createLogoutRequest(LogoutRequest value) {
        return new JAXBElement<LogoutRequest>(_LogoutRequest_QNAME, LogoutRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogoutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "LogoutResponse")
    public JAXBElement<LogoutResponse> createLogoutResponse(LogoutResponse value) {
        return new JAXBElement<LogoutResponse>(_LogoutResponse_QNAME, LogoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "PrepareProcessUserRequest")
    public JAXBElement<UserRequest> createPrepareProcessUserRequest(UserRequest value) {
        return new JAXBElement<UserRequest>(_PrepareProcessUserRequest_QNAME, UserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "PrepareProcessUserResponse")
    public JAXBElement<UserResponse> createPrepareProcessUserResponse(UserResponse value) {
        return new JAXBElement<UserResponse>(_PrepareProcessUserResponse_QNAME, UserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "PrepareCancelUserRequest")
    public JAXBElement<UserRequest> createPrepareCancelUserRequest(UserRequest value) {
        return new JAXBElement<UserRequest>(_PrepareCancelUserRequest_QNAME, UserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "PrepareCancelUserResponse")
    public JAXBElement<UserResponse> createPrepareCancelUserResponse(UserResponse value) {
        return new JAXBElement<UserResponse>(_PrepareCancelUserResponse_QNAME, UserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "ProcessUserRequest")
    public JAXBElement<UserRequest> createProcessUserRequest(UserRequest value) {
        return new JAXBElement<UserRequest>(_ProcessUserRequest_QNAME, UserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REQUESTRETURNType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "ProcessUserResponse")
    public JAXBElement<REQUESTRETURNType> createProcessUserResponse(REQUESTRETURNType value) {
        return new JAXBElement<REQUESTRETURNType>(_ProcessUserResponse_QNAME, REQUESTRETURNType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "CancelUserRequest")
    public JAXBElement<UserRequest> createCancelUserRequest(UserRequest value) {
        return new JAXBElement<UserRequest>(_CancelUserRequest_QNAME, UserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REQUESTRETURNType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "CancelUserResponse")
    public JAXBElement<REQUESTRETURNType> createCancelUserResponse(REQUESTRETURNType value) {
        return new JAXBElement<REQUESTRETURNType>(_CancelUserResponse_QNAME, REQUESTRETURNType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendInvoiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "SendInvoiceRequest")
    public JAXBElement<SendInvoiceRequest> createSendInvoiceRequest(SendInvoiceRequest value) {
        return new JAXBElement<SendInvoiceRequest>(_SendInvoiceRequest_QNAME, SendInvoiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendInvoiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "SendInvoiceResponse")
    public JAXBElement<SendInvoiceResponse> createSendInvoiceResponse(SendInvoiceResponse value) {
        return new JAXBElement<SendInvoiceResponse>(_SendInvoiceResponse_QNAME, SendInvoiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceRequest")
    public JAXBElement<GetInvoiceRequest> createGetInvoiceRequest(GetInvoiceRequest value) {
        return new JAXBElement<GetInvoiceRequest>(_GetInvoiceRequest_QNAME, GetInvoiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceResponse")
    public JAXBElement<GetInvoiceResponse> createGetInvoiceResponse(GetInvoiceResponse value) {
        return new JAXBElement<GetInvoiceResponse>(_GetInvoiceResponse_QNAME, GetInvoiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkInvoiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "MarkInvoiceRequest")
    public JAXBElement<MarkInvoiceRequest> createMarkInvoiceRequest(MarkInvoiceRequest value) {
        return new JAXBElement<MarkInvoiceRequest>(_MarkInvoiceRequest_QNAME, MarkInvoiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkInvoiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "MarkInvoiceResponse")
    public JAXBElement<MarkInvoiceResponse> createMarkInvoiceResponse(MarkInvoiceResponse value) {
        return new JAXBElement<MarkInvoiceResponse>(_MarkInvoiceResponse_QNAME, MarkInvoiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrepareInvoiceResponseRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "PrepareInvoiceResponseRequest")
    public JAXBElement<PrepareInvoiceResponseRequest> createPrepareInvoiceResponseRequest(PrepareInvoiceResponseRequest value) {
        return new JAXBElement<PrepareInvoiceResponseRequest>(_PrepareInvoiceResponseRequest_QNAME, PrepareInvoiceResponseRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrepareInvoiceResponseResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "PrepareInvoiceResponseResponse")
    public JAXBElement<PrepareInvoiceResponseResponse> createPrepareInvoiceResponseResponse(PrepareInvoiceResponseResponse value) {
        return new JAXBElement<PrepareInvoiceResponseResponse>(_PrepareInvoiceResponseResponse_QNAME, PrepareInvoiceResponseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendInvoiceResponseRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "SendInvoiceResponseRequest")
    public JAXBElement<SendInvoiceResponseRequest> createSendInvoiceResponseRequest(SendInvoiceResponseRequest value) {
        return new JAXBElement<SendInvoiceResponseRequest>(_SendInvoiceResponseRequest_QNAME, SendInvoiceResponseRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendInvoiceResponseResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "SendInvoiceResponseResponse")
    public JAXBElement<SendInvoiceResponseResponse> createSendInvoiceResponseResponse(SendInvoiceResponseResponse value) {
        return new JAXBElement<SendInvoiceResponseResponse>(_SendInvoiceResponseResponse_QNAME, SendInvoiceResponseResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendInvoiceResponseWithServerSignRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "SendInvoiceResponseWithServerSignRequest")
    public JAXBElement<SendInvoiceResponseWithServerSignRequest> createSendInvoiceResponseWithServerSignRequest(SendInvoiceResponseWithServerSignRequest value) {
        return new JAXBElement<SendInvoiceResponseWithServerSignRequest>(_SendInvoiceResponseWithServerSignRequest_QNAME, SendInvoiceResponseWithServerSignRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendInvoiceResponseWithServerSignResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "SendInvoiceResponseWithServerSignResponse")
    public JAXBElement<SendInvoiceResponseWithServerSignResponse> createSendInvoiceResponseWithServerSignResponse(SendInvoiceResponseWithServerSignResponse value) {
        return new JAXBElement<SendInvoiceResponseWithServerSignResponse>(_SendInvoiceResponseWithServerSignResponse_QNAME, SendInvoiceResponseWithServerSignResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserListRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetUserListRequest")
    public JAXBElement<GetUserListRequest> createGetUserListRequest(GetUserListRequest value) {
        return new JAXBElement<GetUserListRequest>(_GetUserListRequest_QNAME, GetUserListRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserListResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetUserListResponse")
    public JAXBElement<GetUserListResponse> createGetUserListResponse(GetUserListResponse value) {
        return new JAXBElement<GetUserListResponse>(_GetUserListResponse_QNAME, GetUserListResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserListBinaryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetUserListBinaryRequest")
    public JAXBElement<GetUserListBinaryRequest> createGetUserListBinaryRequest(GetUserListBinaryRequest value) {
        return new JAXBElement<GetUserListBinaryRequest>(_GetUserListBinaryRequest_QNAME, GetUserListBinaryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserListBinaryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetUserListBinaryResponse")
    public JAXBElement<GetUserListBinaryResponse> createGetUserListBinaryResponse(GetUserListBinaryResponse value) {
        return new JAXBElement<GetUserListBinaryResponse>(_GetUserListBinaryResponse_QNAME, GetUserListBinaryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckUserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "CheckUserRequest")
    public JAXBElement<CheckUserRequest> createCheckUserRequest(CheckUserRequest value) {
        return new JAXBElement<CheckUserRequest>(_CheckUserRequest_QNAME, CheckUserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "CheckUserResponse")
    public JAXBElement<CheckUserResponse> createCheckUserResponse(CheckUserResponse value) {
        return new JAXBElement<CheckUserResponse>(_CheckUserResponse_QNAME, CheckUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceStatusRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceStatusRequest")
    public JAXBElement<GetInvoiceStatusRequest> createGetInvoiceStatusRequest(GetInvoiceStatusRequest value) {
        return new JAXBElement<GetInvoiceStatusRequest>(_GetInvoiceStatusRequest_QNAME, GetInvoiceStatusRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceStatusResponse")
    public JAXBElement<GetInvoiceStatusResponse> createGetInvoiceStatusResponse(GetInvoiceStatusResponse value) {
        return new JAXBElement<GetInvoiceStatusResponse>(_GetInvoiceStatusResponse_QNAME, GetInvoiceStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceStatusAllRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceStatusAllRequest")
    public JAXBElement<GetInvoiceStatusAllRequest> createGetInvoiceStatusAllRequest(GetInvoiceStatusAllRequest value) {
        return new JAXBElement<GetInvoiceStatusAllRequest>(_GetInvoiceStatusAllRequest_QNAME, GetInvoiceStatusAllRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceStatusAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceStatusAllResponse")
    public JAXBElement<GetInvoiceStatusAllResponse> createGetInvoiceStatusAllResponse(GetInvoiceStatusAllResponse value) {
        return new JAXBElement<GetInvoiceStatusAllResponse>(_GetInvoiceStatusAllResponse_QNAME, GetInvoiceStatusAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelDraftInvoiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "CancelDraftInvoiceRequest")
    public JAXBElement<CancelDraftInvoiceRequest> createCancelDraftInvoiceRequest(CancelDraftInvoiceRequest value) {
        return new JAXBElement<CancelDraftInvoiceRequest>(_CancelDraftInvoiceRequest_QNAME, CancelDraftInvoiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelDraftInvoiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "CancelDraftInvoiceResponse")
    public JAXBElement<CancelDraftInvoiceResponse> createCancelDraftInvoiceResponse(CancelDraftInvoiceResponse value) {
        return new JAXBElement<CancelDraftInvoiceResponse>(_CancelDraftInvoiceResponse_QNAME, CancelDraftInvoiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadInvoiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "LoadInvoiceRequest")
    public JAXBElement<LoadInvoiceRequest> createLoadInvoiceRequest(LoadInvoiceRequest value) {
        return new JAXBElement<LoadInvoiceRequest>(_LoadInvoiceRequest_QNAME, LoadInvoiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadInvoiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "LoadInvoiceResponse")
    public JAXBElement<LoadInvoiceResponse> createLoadInvoiceResponse(LoadInvoiceResponse value) {
        return new JAXBElement<LoadInvoiceResponse>(_LoadInvoiceResponse_QNAME, LoadInvoiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEnvelopeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetEnvelopeRequest")
    public JAXBElement<GetEnvelopeRequest> createGetEnvelopeRequest(GetEnvelopeRequest value) {
        return new JAXBElement<GetEnvelopeRequest>(_GetEnvelopeRequest_QNAME, GetEnvelopeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEnvelopeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetEnvelopeResponse")
    public JAXBElement<GetEnvelopeResponse> createGetEnvelopeResponse(GetEnvelopeResponse value) {
        return new JAXBElement<GetEnvelopeResponse>(_GetEnvelopeResponse_QNAME, GetEnvelopeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkEnvelopeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "MarkEnvelopeRequest")
    public JAXBElement<MarkEnvelopeRequest> createMarkEnvelopeRequest(MarkEnvelopeRequest value) {
        return new JAXBElement<MarkEnvelopeRequest>(_MarkEnvelopeRequest_QNAME, MarkEnvelopeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkEnvelopeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "MarkEnvelopeResponse")
    public JAXBElement<MarkEnvelopeResponse> createMarkEnvelopeResponse(MarkEnvelopeResponse value) {
        return new JAXBElement<MarkEnvelopeResponse>(_MarkEnvelopeResponse_QNAME, MarkEnvelopeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEnvelopeStatusRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetEnvelopeStatusRequest")
    public JAXBElement<GetEnvelopeStatusRequest> createGetEnvelopeStatusRequest(GetEnvelopeStatusRequest value) {
        return new JAXBElement<GetEnvelopeStatusRequest>(_GetEnvelopeStatusRequest_QNAME, GetEnvelopeStatusRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEnvelopeStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetEnvelopeStatusResponse")
    public JAXBElement<GetEnvelopeStatusResponse> createGetEnvelopeStatusResponse(GetEnvelopeStatusResponse value) {
        return new JAXBElement<GetEnvelopeStatusResponse>(_GetEnvelopeStatusResponse_QNAME, GetEnvelopeStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceWithTypeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceWithTypeRequest")
    public JAXBElement<GetInvoiceWithTypeRequest> createGetInvoiceWithTypeRequest(GetInvoiceWithTypeRequest value) {
        return new JAXBElement<GetInvoiceWithTypeRequest>(_GetInvoiceWithTypeRequest_QNAME, GetInvoiceWithTypeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceWithTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceWithTypeResponse")
    public JAXBElement<GetInvoiceWithTypeResponse> createGetInvoiceWithTypeResponse(GetInvoiceWithTypeResponse value) {
        return new JAXBElement<GetInvoiceWithTypeResponse>(_GetInvoiceWithTypeResponse_QNAME, GetInvoiceWithTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceCountRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceCountRequest")
    public JAXBElement<GetInvoiceCountRequest> createGetInvoiceCountRequest(GetInvoiceCountRequest value) {
        return new JAXBElement<GetInvoiceCountRequest>(_GetInvoiceCountRequest_QNAME, GetInvoiceCountRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInvoiceCountResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.i2i.com/ei/wsdl", name = "GetInvoiceCountResponse")
    public JAXBElement<GetInvoiceCountResponse> createGetInvoiceCountResponse(GetInvoiceCountResponse value) {
        return new JAXBElement<GetInvoiceCountResponse>(_GetInvoiceCountResponse_QNAME, GetInvoiceCountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAppRespRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gib.gov.tr/vedop3/eFatura", name = "getAppRespRequest")
    public JAXBElement<GetAppRespRequestType> createGetAppRespRequest(GetAppRespRequestType value) {
        return new JAXBElement<GetAppRespRequestType>(_GetAppRespRequest_QNAME, GetAppRespRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAppRespResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://gib.gov.tr/vedop3/eFatura", name = "getAppRespResponse")
    public JAXBElement<GetAppRespResponseType> createGetAppRespResponse(GetAppRespResponseType value) {
        return new JAXBElement<GetAppRespResponseType>(_GetAppRespResponse_QNAME, GetAppRespResponseType.class, null, value);
    }

}
