//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aliciType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aliciType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tuzelKisi" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="vkn" type="{http://earsiv.efatura.gov.tr}vknType"/&gt;
 *                   &lt;element name="unvan"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="gercekKisi" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="tckn" type="{http://earsiv.efatura.gov.tr}tcknType"/&gt;
 *                   &lt;element name="adiSoyadi"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tesisatNumarasi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aliciType", namespace = "http://earsiv.efatura.gov.tr", propOrder = {
    "tuzelKisi",
    "gercekKisi",
    "tesisatNumarasi"
})
public class AliciType {

    @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
    protected AliciType.TuzelKisi tuzelKisi;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
    protected AliciType.GercekKisi gercekKisi;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
    protected String tesisatNumarasi;

    /**
     * Gets the value of the tuzelKisi property.
     * 
     * @return
     *     possible object is
     *     {@link AliciType.TuzelKisi }
     *     
     */
    public AliciType.TuzelKisi getTuzelKisi() {
        return tuzelKisi;
    }

    /**
     * Sets the value of the tuzelKisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliciType.TuzelKisi }
     *     
     */
    public void setTuzelKisi(AliciType.TuzelKisi value) {
        this.tuzelKisi = value;
    }

    /**
     * Gets the value of the gercekKisi property.
     * 
     * @return
     *     possible object is
     *     {@link AliciType.GercekKisi }
     *     
     */
    public AliciType.GercekKisi getGercekKisi() {
        return gercekKisi;
    }

    /**
     * Sets the value of the gercekKisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliciType.GercekKisi }
     *     
     */
    public void setGercekKisi(AliciType.GercekKisi value) {
        this.gercekKisi = value;
    }

    /**
     * Gets the value of the tesisatNumarasi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTesisatNumarasi() {
        return tesisatNumarasi;
    }

    /**
     * Sets the value of the tesisatNumarasi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTesisatNumarasi(String value) {
        this.tesisatNumarasi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="tckn" type="{http://earsiv.efatura.gov.tr}tcknType"/&gt;
     *         &lt;element name="adiSoyadi"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tckn",
        "adiSoyadi"
    })
    public static class GercekKisi {

        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected String tckn;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected String adiSoyadi;

        /**
         * Gets the value of the tckn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTckn() {
            return tckn;
        }

        /**
         * Sets the value of the tckn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTckn(String value) {
            this.tckn = value;
        }

        /**
         * Gets the value of the adiSoyadi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdiSoyadi() {
            return adiSoyadi;
        }

        /**
         * Sets the value of the adiSoyadi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdiSoyadi(String value) {
            this.adiSoyadi = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="vkn" type="{http://earsiv.efatura.gov.tr}vknType"/&gt;
     *         &lt;element name="unvan"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vkn",
        "unvan"
    })
    public static class TuzelKisi {

        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected String vkn;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected String unvan;

        /**
         * Gets the value of the vkn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVkn() {
            return vkn;
        }

        /**
         * Sets the value of the vkn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVkn(String value) {
            this.vkn = value;
        }

        /**
         * Gets the value of the unvan property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnvan() {
            return unvan;
        }

        /**
         * Sets the value of the unvan property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnvan(String value) {
            this.unvan = value;
        }

    }

}
