//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CancelEArchiveInvoiceRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancelEArchiveInvoiceRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="REQUEST_HEADER" type="{http://schemas.i2i.com/ei/entity}REQUEST_HEADERType"/&gt;
 *         &lt;element name="CancelEArsivInvoiceContent" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="UPLOAD_FLAG" type="{http://schemas.i2i.com/ei/wsdl/archive}FLAG_VALUE" minOccurs="0"/&gt;
 *                   &lt;element name="FATURA_UUID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FATURA_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="EARSIV_CANCEL_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="DELETE_FLAG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="IPTAL_TARIHI" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                   &lt;element name="TOPLAM_TUTAR" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="INVOICE_CONTENT" type="{http://www.w3.org/2005/05/xmlmime}base64Binary" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelEArchiveInvoiceRequest", propOrder = {
    "requestheader",
    "cancelEArsivInvoiceContent"
})
public class CancelEArchiveInvoiceRequest {

    @XmlElement(name = "REQUEST_HEADER", required = true)
    protected REQUESTHEADERType requestheader;
    @XmlElement(name = "CancelEArsivInvoiceContent", required = true)
    protected List<CancelEArchiveInvoiceRequest.CancelEArsivInvoiceContent> cancelEArsivInvoiceContent;

    /**
     * Gets the value of the requestheader property.
     * 
     * @return
     *     possible object is
     *     {@link REQUESTHEADERType }
     *     
     */
    public REQUESTHEADERType getREQUESTHEADER() {
        return requestheader;
    }

    /**
     * Sets the value of the requestheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link REQUESTHEADERType }
     *     
     */
    public void setREQUESTHEADER(REQUESTHEADERType value) {
        this.requestheader = value;
    }

    /**
     * Gets the value of the cancelEArsivInvoiceContent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cancelEArsivInvoiceContent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCancelEArsivInvoiceContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CancelEArchiveInvoiceRequest.CancelEArsivInvoiceContent }
     * 
     * 
     */
    public List<CancelEArchiveInvoiceRequest.CancelEArsivInvoiceContent> getCancelEArsivInvoiceContent() {
        if (cancelEArsivInvoiceContent == null) {
            cancelEArsivInvoiceContent = new ArrayList<CancelEArchiveInvoiceRequest.CancelEArsivInvoiceContent>();
        }
        return this.cancelEArsivInvoiceContent;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="UPLOAD_FLAG" type="{http://schemas.i2i.com/ei/wsdl/archive}FLAG_VALUE" minOccurs="0"/&gt;
     *         &lt;element name="FATURA_UUID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FATURA_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="EARSIV_CANCEL_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="DELETE_FLAG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="IPTAL_TARIHI" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *         &lt;element name="TOPLAM_TUTAR" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="INVOICE_CONTENT" type="{http://www.w3.org/2005/05/xmlmime}base64Binary" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uploadflag",
        "faturauuid",
        "faturaid",
        "earsivcancelemail",
        "deleteflag",
        "iptaltarihi",
        "toplamtutar",
        "invoicecontent"
    })
    public static class CancelEArsivInvoiceContent {

        @XmlElement(name = "UPLOAD_FLAG")
        @XmlSchemaType(name = "string")
        protected FLAGVALUE uploadflag;
        @XmlElement(name = "FATURA_UUID", required = true)
        protected String faturauuid;
        @XmlElement(name = "FATURA_ID")
        protected String faturaid;
        @XmlElement(name = "EARSIV_CANCEL_EMAIL")
        protected String earsivcancelemail;
        @XmlElement(name = "DELETE_FLAG")
        protected String deleteflag;
        @XmlElement(name = "IPTAL_TARIHI")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar iptaltarihi;
        @XmlElement(name = "TOPLAM_TUTAR")
        protected BigDecimal toplamtutar;
        @XmlElement(name = "INVOICE_CONTENT")
        protected Base64Binary invoicecontent;

        /**
         * Gets the value of the uploadflag property.
         * 
         * @return
         *     possible object is
         *     {@link FLAGVALUE }
         *     
         */
        public FLAGVALUE getUPLOADFLAG() {
            return uploadflag;
        }

        /**
         * Sets the value of the uploadflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link FLAGVALUE }
         *     
         */
        public void setUPLOADFLAG(FLAGVALUE value) {
            this.uploadflag = value;
        }

        /**
         * Gets the value of the faturauuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFATURAUUID() {
            return faturauuid;
        }

        /**
         * Sets the value of the faturauuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFATURAUUID(String value) {
            this.faturauuid = value;
        }

        /**
         * Gets the value of the faturaid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFATURAID() {
            return faturaid;
        }

        /**
         * Sets the value of the faturaid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFATURAID(String value) {
            this.faturaid = value;
        }

        /**
         * Gets the value of the earsivcancelemail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEARSIVCANCELEMAIL() {
            return earsivcancelemail;
        }

        /**
         * Sets the value of the earsivcancelemail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEARSIVCANCELEMAIL(String value) {
            this.earsivcancelemail = value;
        }

        /**
         * Gets the value of the deleteflag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDELETEFLAG() {
            return deleteflag;
        }

        /**
         * Sets the value of the deleteflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDELETEFLAG(String value) {
            this.deleteflag = value;
        }

        /**
         * Gets the value of the iptaltarihi property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getIPTALTARIHI() {
            return iptaltarihi;
        }

        /**
         * Sets the value of the iptaltarihi property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setIPTALTARIHI(XMLGregorianCalendar value) {
            this.iptaltarihi = value;
        }

        /**
         * Gets the value of the toplamtutar property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTOPLAMTUTAR() {
            return toplamtutar;
        }

        /**
         * Sets the value of the toplamtutar property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTOPLAMTUTAR(BigDecimal value) {
            this.toplamtutar = value;
        }

        /**
         * Gets the value of the invoicecontent property.
         * 
         * @return
         *     possible object is
         *     {@link Base64Binary }
         *     
         */
        public Base64Binary getINVOICECONTENT() {
            return invoicecontent;
        }

        /**
         * Sets the value of the invoicecontent property.
         * 
         * @param value
         *     allowed object is
         *     {@link Base64Binary }
         *     
         */
        public void setINVOICECONTENT(Base64Binary value) {
            this.invoicecontent = value;
        }

    }

}
