//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancelEDefterRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancelEDefterRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="REQUEST_HEADER" type="{http://schemas.i2i.com/ei/entity}REQUEST_HEADERType"/&gt;
 *         &lt;element name="CancelEDefterContent" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VKN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="DONEM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelEDefterRequest", propOrder = {
    "requestheader",
    "cancelEDefterContent"
})
public class CancelEDefterRequest {

    @XmlElement(name = "REQUEST_HEADER", required = true)
    protected REQUESTHEADERType requestheader;
    @XmlElement(name = "CancelEDefterContent", required = true)
    protected List<CancelEDefterRequest.CancelEDefterContent> cancelEDefterContent;

    /**
     * Gets the value of the requestheader property.
     * 
     * @return
     *     possible object is
     *     {@link REQUESTHEADERType }
     *     
     */
    public REQUESTHEADERType getREQUESTHEADER() {
        return requestheader;
    }

    /**
     * Sets the value of the requestheader property.
     * 
     * @param value
     *     allowed object is
     *     {@link REQUESTHEADERType }
     *     
     */
    public void setREQUESTHEADER(REQUESTHEADERType value) {
        this.requestheader = value;
    }

    /**
     * Gets the value of the cancelEDefterContent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cancelEDefterContent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCancelEDefterContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CancelEDefterRequest.CancelEDefterContent }
     * 
     * 
     */
    public List<CancelEDefterRequest.CancelEDefterContent> getCancelEDefterContent() {
        if (cancelEDefterContent == null) {
            cancelEDefterContent = new ArrayList<CancelEDefterRequest.CancelEDefterContent>();
        }
        return this.cancelEDefterContent;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VKN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="DONEM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vkn",
        "donem"
    })
    public static class CancelEDefterContent {

        @XmlElement(name = "VKN", required = true)
        protected String vkn;
        @XmlElement(name = "DONEM", required = true)
        protected String donem;

        /**
         * Gets the value of the vkn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVKN() {
            return vkn;
        }

        /**
         * Sets the value of the vkn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVKN(String value) {
            this.vkn = value;
        }

        /**
         * Gets the value of the donem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDONEM() {
            return donem;
        }

        /**
         * Sets the value of the donem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDONEM(String value) {
            this.donem = value;
        }

    }

}
