//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DOC_TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DOC_TYPE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="KEBIR DEFTERI"/&gt;
 *     &lt;enumeration value="YEVMIYE DEFTERI"/&gt;
 *     &lt;enumeration value="KEBIR BERATI"/&gt;
 *     &lt;enumeration value="YEVMIYE BERATI"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DOC_TYPE")
@XmlEnum
public enum DOCTYPE {

    @XmlEnumValue("KEBIR DEFTERI")
    KEBIR_DEFTERI("KEBIR DEFTERI"),
    @XmlEnumValue("YEVMIYE DEFTERI")
    YEVMIYE_DEFTERI("YEVMIYE DEFTERI"),
    @XmlEnumValue("KEBIR BERATI")
    KEBIR_BERATI("KEBIR BERATI"),
    @XmlEnumValue("YEVMIYE BERATI")
    YEVMIYE_BERATI("YEVMIYE BERATI");
    private final String value;

    DOCTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DOCTYPE fromValue(String v) {
        for (DOCTYPE c: DOCTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
