//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EARSIV_PROPERTIES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EARSIV_PROPERTIES"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EARSIV_TYPE" type="{http://schemas.i2i.com/ei/wsdl/archive}EARSIV_TYPE_VALUE"/&gt;
 *         &lt;element name="EARSIV_EMAIL_FLAG" type="{http://schemas.i2i.com/ei/wsdl/archive}FLAG_VALUE" minOccurs="0"/&gt;
 *         &lt;element name="EARSIV_EMAIL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SUB_STATUS" type="{http://schemas.i2i.com/ei/wsdl/archive}SUB_STATUS_VALUE" minOccurs="0"/&gt;
 *         &lt;element name="ARCH_INVOICE_ID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="SERI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EARCHIVE_TEST_FLAG" type="{http://schemas.i2i.com/ei/wsdl/archive}FLAG_VALUE" minOccurs="0"/&gt;
 *         &lt;element name="EARSIV_SMS_FLAG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SMS_PHONE_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VALIDATION_FLAG" type="{http://schemas.i2i.com/ei/wsdl/archive}FLAG_VALUE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EARSIV_PROPERTIES", propOrder = {
    "earsivtype",
    "earsivemailflag",
    "earsivemail",
    "substatus",
    "archinvoiceid",
    "seri",
    "earchivetestflag",
    "earsivsmsflag",
    "smsphonenumber",
    "validationflag"
})
public class EARSIVPROPERTIES {

    @XmlElement(name = "EARSIV_TYPE", required = true)
    @XmlSchemaType(name = "string")
    protected EARSIVTYPEVALUE earsivtype;
    @XmlElement(name = "EARSIV_EMAIL_FLAG", defaultValue = "N")
    @XmlSchemaType(name = "string")
    protected FLAGVALUE earsivemailflag;
    @XmlElement(name = "EARSIV_EMAIL")
    protected List<String> earsivemail;
    @XmlElement(name = "SUB_STATUS", defaultValue = "NEW")
    @XmlSchemaType(name = "string")
    protected SUBSTATUSVALUE substatus;
    @XmlElement(name = "ARCH_INVOICE_ID")
    protected Integer archinvoiceid;
    @XmlElement(name = "SERI")
    protected String seri;
    @XmlElement(name = "EARCHIVE_TEST_FLAG")
    @XmlSchemaType(name = "string")
    protected FLAGVALUE earchivetestflag;
    @XmlElement(name = "EARSIV_SMS_FLAG")
    protected String earsivsmsflag;
    @XmlElement(name = "SMS_PHONE_NUMBER")
    protected String smsphonenumber;
    @XmlElement(name = "VALIDATION_FLAG")
    @XmlSchemaType(name = "string")
    protected FLAGVALUE validationflag;

    /**
     * Gets the value of the earsivtype property.
     * 
     * @return
     *     possible object is
     *     {@link EARSIVTYPEVALUE }
     *     
     */
    public EARSIVTYPEVALUE getEARSIVTYPE() {
        return earsivtype;
    }

    /**
     * Sets the value of the earsivtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link EARSIVTYPEVALUE }
     *     
     */
    public void setEARSIVTYPE(EARSIVTYPEVALUE value) {
        this.earsivtype = value;
    }

    /**
     * Gets the value of the earsivemailflag property.
     * 
     * @return
     *     possible object is
     *     {@link FLAGVALUE }
     *     
     */
    public FLAGVALUE getEARSIVEMAILFLAG() {
        return earsivemailflag;
    }

    /**
     * Sets the value of the earsivemailflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLAGVALUE }
     *     
     */
    public void setEARSIVEMAILFLAG(FLAGVALUE value) {
        this.earsivemailflag = value;
    }

    /**
     * Gets the value of the earsivemail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the earsivemail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEARSIVEMAIL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEARSIVEMAIL() {
        if (earsivemail == null) {
            earsivemail = new ArrayList<String>();
        }
        return this.earsivemail;
    }

    /**
     * Gets the value of the substatus property.
     * 
     * @return
     *     possible object is
     *     {@link SUBSTATUSVALUE }
     *     
     */
    public SUBSTATUSVALUE getSUBSTATUS() {
        return substatus;
    }

    /**
     * Sets the value of the substatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUBSTATUSVALUE }
     *     
     */
    public void setSUBSTATUS(SUBSTATUSVALUE value) {
        this.substatus = value;
    }

    /**
     * Gets the value of the archinvoiceid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getARCHINVOICEID() {
        return archinvoiceid;
    }

    /**
     * Sets the value of the archinvoiceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setARCHINVOICEID(Integer value) {
        this.archinvoiceid = value;
    }

    /**
     * Gets the value of the seri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERI() {
        return seri;
    }

    /**
     * Sets the value of the seri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERI(String value) {
        this.seri = value;
    }

    /**
     * Gets the value of the earchivetestflag property.
     * 
     * @return
     *     possible object is
     *     {@link FLAGVALUE }
     *     
     */
    public FLAGVALUE getEARCHIVETESTFLAG() {
        return earchivetestflag;
    }

    /**
     * Sets the value of the earchivetestflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLAGVALUE }
     *     
     */
    public void setEARCHIVETESTFLAG(FLAGVALUE value) {
        this.earchivetestflag = value;
    }

    /**
     * Gets the value of the earsivsmsflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEARSIVSMSFLAG() {
        return earsivsmsflag;
    }

    /**
     * Sets the value of the earsivsmsflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEARSIVSMSFLAG(String value) {
        this.earsivsmsflag = value;
    }

    /**
     * Gets the value of the smsphonenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMSPHONENUMBER() {
        return smsphonenumber;
    }

    /**
     * Sets the value of the smsphonenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMSPHONENUMBER(String value) {
        this.smsphonenumber = value;
    }

    /**
     * Gets the value of the validationflag property.
     * 
     * @return
     *     possible object is
     *     {@link FLAGVALUE }
     *     
     */
    public FLAGVALUE getVALIDATIONFLAG() {
        return validationflag;
    }

    /**
     * Sets the value of the validationflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLAGVALUE }
     *     
     */
    public void setVALIDATIONFLAG(FLAGVALUE value) {
        this.validationflag = value;
    }

}
