//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for faturaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faturaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="faturaNo" type="{http://earsiv.efatura.gov.tr}idType"/&gt;
 *         &lt;element name="gonderimSekli"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="KAGIT"/&gt;
 *               &lt;enumeration value="ELEKTRONIK"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dosyaAdi" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ozetDeger" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="duzenlenmeTarihi" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="duzenlenmeZamani" type="{http://earsiv.efatura.gov.tr}timeType"/&gt;
 *         &lt;element name="toplamTutar"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="18"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="odenecekTutar"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="18"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="paraBirimi"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="AED"/&gt;
 *               &lt;enumeration value="AFN"/&gt;
 *               &lt;enumeration value="ALL"/&gt;
 *               &lt;enumeration value="AMD"/&gt;
 *               &lt;enumeration value="ANG"/&gt;
 *               &lt;enumeration value="AOA"/&gt;
 *               &lt;enumeration value="ARS"/&gt;
 *               &lt;enumeration value="AUD"/&gt;
 *               &lt;enumeration value="AWG"/&gt;
 *               &lt;enumeration value="AZN"/&gt;
 *               &lt;enumeration value="BAM"/&gt;
 *               &lt;enumeration value="BBD"/&gt;
 *               &lt;enumeration value="BDT"/&gt;
 *               &lt;enumeration value="BGN"/&gt;
 *               &lt;enumeration value="BHD"/&gt;
 *               &lt;enumeration value="BIF"/&gt;
 *               &lt;enumeration value="BMD"/&gt;
 *               &lt;enumeration value="BND"/&gt;
 *               &lt;enumeration value="BOB"/&gt;
 *               &lt;enumeration value="BOV"/&gt;
 *               &lt;enumeration value="BRL"/&gt;
 *               &lt;enumeration value="BSD"/&gt;
 *               &lt;enumeration value="BTN"/&gt;
 *               &lt;enumeration value="BWP"/&gt;
 *               &lt;enumeration value="BYR"/&gt;
 *               &lt;enumeration value="BZD"/&gt;
 *               &lt;enumeration value="CAD"/&gt;
 *               &lt;enumeration value="CDF"/&gt;
 *               &lt;enumeration value="CHE"/&gt;
 *               &lt;enumeration value="CHF"/&gt;
 *               &lt;enumeration value="CHW"/&gt;
 *               &lt;enumeration value="CLF"/&gt;
 *               &lt;enumeration value="CLP"/&gt;
 *               &lt;enumeration value="CNY"/&gt;
 *               &lt;enumeration value="COP"/&gt;
 *               &lt;enumeration value="COU"/&gt;
 *               &lt;enumeration value="CRC"/&gt;
 *               &lt;enumeration value="CUC"/&gt;
 *               &lt;enumeration value="CUP"/&gt;
 *               &lt;enumeration value="CVE"/&gt;
 *               &lt;enumeration value="CZK"/&gt;
 *               &lt;enumeration value="DJF"/&gt;
 *               &lt;enumeration value="DKK"/&gt;
 *               &lt;enumeration value="DOP"/&gt;
 *               &lt;enumeration value="DZD"/&gt;
 *               &lt;enumeration value="EGP"/&gt;
 *               &lt;enumeration value="ERN"/&gt;
 *               &lt;enumeration value="ETB"/&gt;
 *               &lt;enumeration value="EUR"/&gt;
 *               &lt;enumeration value="FJD"/&gt;
 *               &lt;enumeration value="FKP"/&gt;
 *               &lt;enumeration value="GBP"/&gt;
 *               &lt;enumeration value="GEL"/&gt;
 *               &lt;enumeration value="GHS"/&gt;
 *               &lt;enumeration value="GIP"/&gt;
 *               &lt;enumeration value="GMD"/&gt;
 *               &lt;enumeration value="GNF"/&gt;
 *               &lt;enumeration value="GTQ"/&gt;
 *               &lt;enumeration value="GYD"/&gt;
 *               &lt;enumeration value="HKD"/&gt;
 *               &lt;enumeration value="HNL"/&gt;
 *               &lt;enumeration value="HRK"/&gt;
 *               &lt;enumeration value="HTG"/&gt;
 *               &lt;enumeration value="HUF"/&gt;
 *               &lt;enumeration value="IDR"/&gt;
 *               &lt;enumeration value="ILS"/&gt;
 *               &lt;enumeration value="INR"/&gt;
 *               &lt;enumeration value="IQD"/&gt;
 *               &lt;enumeration value="IRR"/&gt;
 *               &lt;enumeration value="ISK"/&gt;
 *               &lt;enumeration value="JMD"/&gt;
 *               &lt;enumeration value="JOD"/&gt;
 *               &lt;enumeration value="JPY"/&gt;
 *               &lt;enumeration value="KES"/&gt;
 *               &lt;enumeration value="KGS"/&gt;
 *               &lt;enumeration value="KHR"/&gt;
 *               &lt;enumeration value="KMF"/&gt;
 *               &lt;enumeration value="KPW"/&gt;
 *               &lt;enumeration value="KRW"/&gt;
 *               &lt;enumeration value="KWD"/&gt;
 *               &lt;enumeration value="KYD"/&gt;
 *               &lt;enumeration value="KZT"/&gt;
 *               &lt;enumeration value="LAK"/&gt;
 *               &lt;enumeration value="LBP"/&gt;
 *               &lt;enumeration value="LKR"/&gt;
 *               &lt;enumeration value="LRD"/&gt;
 *               &lt;enumeration value="LSL"/&gt;
 *               &lt;enumeration value="LTL"/&gt;
 *               &lt;enumeration value="LVL"/&gt;
 *               &lt;enumeration value="LYD"/&gt;
 *               &lt;enumeration value="MAD"/&gt;
 *               &lt;enumeration value="MDL"/&gt;
 *               &lt;enumeration value="MGA"/&gt;
 *               &lt;enumeration value="MKD"/&gt;
 *               &lt;enumeration value="MMK"/&gt;
 *               &lt;enumeration value="MNT"/&gt;
 *               &lt;enumeration value="MOP"/&gt;
 *               &lt;enumeration value="MRO"/&gt;
 *               &lt;enumeration value="MUR"/&gt;
 *               &lt;enumeration value="MVR"/&gt;
 *               &lt;enumeration value="MWK"/&gt;
 *               &lt;enumeration value="MXN"/&gt;
 *               &lt;enumeration value="MXV"/&gt;
 *               &lt;enumeration value="MYR"/&gt;
 *               &lt;enumeration value="MZN"/&gt;
 *               &lt;enumeration value="NAD"/&gt;
 *               &lt;enumeration value="NGN"/&gt;
 *               &lt;enumeration value="NIO"/&gt;
 *               &lt;enumeration value="NOK"/&gt;
 *               &lt;enumeration value="NPR"/&gt;
 *               &lt;enumeration value="NZD"/&gt;
 *               &lt;enumeration value="OMR"/&gt;
 *               &lt;enumeration value="PAB"/&gt;
 *               &lt;enumeration value="PEN"/&gt;
 *               &lt;enumeration value="PGK"/&gt;
 *               &lt;enumeration value="PHP"/&gt;
 *               &lt;enumeration value="PKR"/&gt;
 *               &lt;enumeration value="PLN"/&gt;
 *               &lt;enumeration value="PYG"/&gt;
 *               &lt;enumeration value="QAR"/&gt;
 *               &lt;enumeration value="RON"/&gt;
 *               &lt;enumeration value="RSD"/&gt;
 *               &lt;enumeration value="RUB"/&gt;
 *               &lt;enumeration value="RWF"/&gt;
 *               &lt;enumeration value="SAR"/&gt;
 *               &lt;enumeration value="SBD"/&gt;
 *               &lt;enumeration value="SCR"/&gt;
 *               &lt;enumeration value="SDG"/&gt;
 *               &lt;enumeration value="SEK"/&gt;
 *               &lt;enumeration value="SGD"/&gt;
 *               &lt;enumeration value="SHP"/&gt;
 *               &lt;enumeration value="SLL"/&gt;
 *               &lt;enumeration value="SOS"/&gt;
 *               &lt;enumeration value="SRD"/&gt;
 *               &lt;enumeration value="SSP"/&gt;
 *               &lt;enumeration value="STD"/&gt;
 *               &lt;enumeration value="SVC"/&gt;
 *               &lt;enumeration value="SYP"/&gt;
 *               &lt;enumeration value="SZL"/&gt;
 *               &lt;enumeration value="THB"/&gt;
 *               &lt;enumeration value="TJS"/&gt;
 *               &lt;enumeration value="TMT"/&gt;
 *               &lt;enumeration value="TND"/&gt;
 *               &lt;enumeration value="TOP"/&gt;
 *               &lt;enumeration value="TRY"/&gt;
 *               &lt;enumeration value="TTD"/&gt;
 *               &lt;enumeration value="TWD"/&gt;
 *               &lt;enumeration value="TZS"/&gt;
 *               &lt;enumeration value="UAH"/&gt;
 *               &lt;enumeration value="UGX"/&gt;
 *               &lt;enumeration value="USD"/&gt;
 *               &lt;enumeration value="USN"/&gt;
 *               &lt;enumeration value="USS"/&gt;
 *               &lt;enumeration value="UYI"/&gt;
 *               &lt;enumeration value="UYU"/&gt;
 *               &lt;enumeration value="UZS"/&gt;
 *               &lt;enumeration value="VEF"/&gt;
 *               &lt;enumeration value="VND"/&gt;
 *               &lt;enumeration value="VUV"/&gt;
 *               &lt;enumeration value="WST"/&gt;
 *               &lt;enumeration value="XAF"/&gt;
 *               &lt;enumeration value="XAG"/&gt;
 *               &lt;enumeration value="XAU"/&gt;
 *               &lt;enumeration value="XBA"/&gt;
 *               &lt;enumeration value="XBB"/&gt;
 *               &lt;enumeration value="XBC"/&gt;
 *               &lt;enumeration value="XBD"/&gt;
 *               &lt;enumeration value="XCD"/&gt;
 *               &lt;enumeration value="XDR"/&gt;
 *               &lt;enumeration value="XFU"/&gt;
 *               &lt;enumeration value="XOF"/&gt;
 *               &lt;enumeration value="XPD"/&gt;
 *               &lt;enumeration value="XPF"/&gt;
 *               &lt;enumeration value="XPT"/&gt;
 *               &lt;enumeration value="XSU"/&gt;
 *               &lt;enumeration value="XTS"/&gt;
 *               &lt;enumeration value="XUA"/&gt;
 *               &lt;enumeration value="XXX"/&gt;
 *               &lt;enumeration value="YER"/&gt;
 *               &lt;enumeration value="ZAR"/&gt;
 *               &lt;enumeration value="ZMK"/&gt;
 *               &lt;enumeration value="ZWL"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vergiBilgisi"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="vergilerToplami"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                         &lt;totalDigits value="18"/&gt;
 *                         &lt;fractionDigits value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="vergi" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="matrah"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                                   &lt;totalDigits value="18"/&gt;
 *                                   &lt;fractionDigits value="2"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="vergiKodu"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="0003"/&gt;
 *                                   &lt;enumeration value="0015"/&gt;
 *                                   &lt;enumeration value="0061"/&gt;
 *                                   &lt;enumeration value="0071"/&gt;
 *                                   &lt;enumeration value="0073"/&gt;
 *                                   &lt;enumeration value="0074"/&gt;
 *                                   &lt;enumeration value="0075"/&gt;
 *                                   &lt;enumeration value="0076"/&gt;
 *                                   &lt;enumeration value="0077"/&gt;
 *                                   &lt;enumeration value="1047"/&gt;
 *                                   &lt;enumeration value="1048"/&gt;
 *                                   &lt;enumeration value="4080"/&gt;
 *                                   &lt;enumeration value="4081"/&gt;
 *                                   &lt;enumeration value="4171"/&gt;
 *                                   &lt;enumeration value="9015"/&gt;
 *                                   &lt;enumeration value="9021"/&gt;
 *                                   &lt;enumeration value="9077"/&gt;
 *                                   &lt;enumeration value="8001"/&gt;
 *                                   &lt;enumeration value="8002"/&gt;
 *                                   &lt;enumeration value="8003"/&gt;
 *                                   &lt;enumeration value="8004"/&gt;
 *                                   &lt;enumeration value="8005"/&gt;
 *                                   &lt;enumeration value="8006"/&gt;
 *                                   &lt;enumeration value="8007"/&gt;
 *                                   &lt;enumeration value="8008"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="vergiTutari"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                                   &lt;totalDigits value="18"/&gt;
 *                                   &lt;fractionDigits value="2"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="vergiOrani"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                   &lt;totalDigits value="3"/&gt;
 *                                   &lt;maxInclusive value="100"/&gt;
 *                                   &lt;minInclusive value="0"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="tevkifat" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="tevkifatKodu"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="301"/&gt;
 *                                   &lt;enumeration value="302"/&gt;
 *                                   &lt;enumeration value="303"/&gt;
 *                                   &lt;enumeration value="304"/&gt;
 *                                   &lt;enumeration value="305"/&gt;
 *                                   &lt;enumeration value="306"/&gt;
 *                                   &lt;enumeration value="308"/&gt;
 *                                   &lt;enumeration value="309"/&gt;
 *                                   &lt;enumeration value="310"/&gt;
 *                                   &lt;enumeration value="311"/&gt;
 *                                   &lt;enumeration value="312"/&gt;
 *                                   &lt;enumeration value="313"/&gt;
 *                                   &lt;enumeration value="314"/&gt;
 *                                   &lt;enumeration value="315"/&gt;
 *                                   &lt;enumeration value="316"/&gt;
 *                                   &lt;enumeration value="317"/&gt;
 *                                   &lt;enumeration value="318"/&gt;
 *                                   &lt;enumeration value="319"/&gt;
 *                                   &lt;enumeration value="320"/&gt;
 *                                   &lt;enumeration value="321"/&gt;
 *                                   &lt;enumeration value="350"/&gt;
 *                                   &lt;enumeration value="601"/&gt;
 *                                   &lt;enumeration value="602"/&gt;
 *                                   &lt;enumeration value="603"/&gt;
 *                                   &lt;enumeration value="604"/&gt;
 *                                   &lt;enumeration value="605"/&gt;
 *                                   &lt;enumeration value="606"/&gt;
 *                                   &lt;enumeration value="607"/&gt;
 *                                   &lt;enumeration value="608"/&gt;
 *                                   &lt;enumeration value="609"/&gt;
 *                                   &lt;enumeration value="610"/&gt;
 *                                   &lt;enumeration value="611"/&gt;
 *                                   &lt;enumeration value="612"/&gt;
 *                                   &lt;enumeration value="613"/&gt;
 *                                   &lt;enumeration value="614"/&gt;
 *                                   &lt;enumeration value="615"/&gt;
 *                                   &lt;enumeration value="616"/&gt;
 *                                   &lt;enumeration value="617"/&gt;
 *                                   &lt;enumeration value="618"/&gt;
 *                                   &lt;enumeration value="619"/&gt;
 *                                   &lt;enumeration value="620"/&gt;
 *                                   &lt;enumeration value="621"/&gt;
 *                                   &lt;enumeration value="622"/&gt;
 *                                   &lt;enumeration value="623"/&gt;
 *                                   &lt;enumeration value="650"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="tevkifatTutari"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                                   &lt;totalDigits value="18"/&gt;
 *                                   &lt;fractionDigits value="2"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="tevkifatOrani"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                                   &lt;totalDigits value="5"/&gt;
 *                                   &lt;fractionDigits value="2"/&gt;
 *                                   &lt;maxInclusive value="100"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="aliciBilgileri" type="{http://earsiv.efatura.gov.tr}aliciType"/&gt;
 *         &lt;element name="internetSatisBilgi" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="webAdresi"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="odemeSekli" type="{http://earsiv.efatura.gov.tr}odemeTip"/&gt;
 *                   &lt;element name="odemeAracisiAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="odemeTarihi" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="gonderiBilgileri" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="gonderimTarihi" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="gonderiTasiyan" type="{http://earsiv.efatura.gov.tr}kisiType"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ynOkcFisBilgisi" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="okcSeriNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="zNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="fisNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="fisTarih" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faturaType", namespace = "http://earsiv.efatura.gov.tr", propOrder = {
    "faturaNo",
    "gonderimSekli",
    "dosyaAdi",
    "ozetDeger",
    "duzenlenmeTarihi",
    "duzenlenmeZamani",
    "toplamTutar",
    "odenecekTutar",
    "paraBirimi",
    "vergiBilgisi",
    "aliciBilgileri",
    "internetSatisBilgi",
    "ynOkcFisBilgisi"
})
public class FaturaType {

    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected String faturaNo;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected String gonderimSekli;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected String dosyaAdi;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected String ozetDeger;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar duzenlenmeTarihi;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar duzenlenmeZamani;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected BigDecimal toplamTutar;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected BigDecimal odenecekTutar;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected String paraBirimi;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected FaturaType.VergiBilgisi vergiBilgisi;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected AliciType aliciBilgileri;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
    protected FaturaType.InternetSatisBilgi internetSatisBilgi;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
    protected FaturaType.YnOkcFisBilgisi ynOkcFisBilgisi;

    /**
     * Gets the value of the faturaNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaturaNo() {
        return faturaNo;
    }

    /**
     * Sets the value of the faturaNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaturaNo(String value) {
        this.faturaNo = value;
    }

    /**
     * Gets the value of the gonderimSekli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGonderimSekli() {
        return gonderimSekli;
    }

    /**
     * Sets the value of the gonderimSekli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGonderimSekli(String value) {
        this.gonderimSekli = value;
    }

    /**
     * Gets the value of the dosyaAdi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDosyaAdi() {
        return dosyaAdi;
    }

    /**
     * Sets the value of the dosyaAdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDosyaAdi(String value) {
        this.dosyaAdi = value;
    }

    /**
     * Gets the value of the ozetDeger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOzetDeger() {
        return ozetDeger;
    }

    /**
     * Sets the value of the ozetDeger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOzetDeger(String value) {
        this.ozetDeger = value;
    }

    /**
     * Gets the value of the duzenlenmeTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDuzenlenmeTarihi() {
        return duzenlenmeTarihi;
    }

    /**
     * Sets the value of the duzenlenmeTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDuzenlenmeTarihi(XMLGregorianCalendar value) {
        this.duzenlenmeTarihi = value;
    }

    /**
     * Gets the value of the duzenlenmeZamani property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDuzenlenmeZamani() {
        return duzenlenmeZamani;
    }

    /**
     * Sets the value of the duzenlenmeZamani property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDuzenlenmeZamani(XMLGregorianCalendar value) {
        this.duzenlenmeZamani = value;
    }

    /**
     * Gets the value of the toplamTutar property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getToplamTutar() {
        return toplamTutar;
    }

    /**
     * Sets the value of the toplamTutar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setToplamTutar(BigDecimal value) {
        this.toplamTutar = value;
    }

    /**
     * Gets the value of the odenecekTutar property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOdenecekTutar() {
        return odenecekTutar;
    }

    /**
     * Sets the value of the odenecekTutar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOdenecekTutar(BigDecimal value) {
        this.odenecekTutar = value;
    }

    /**
     * Gets the value of the paraBirimi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParaBirimi() {
        return paraBirimi;
    }

    /**
     * Sets the value of the paraBirimi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParaBirimi(String value) {
        this.paraBirimi = value;
    }

    /**
     * Gets the value of the vergiBilgisi property.
     * 
     * @return
     *     possible object is
     *     {@link FaturaType.VergiBilgisi }
     *     
     */
    public FaturaType.VergiBilgisi getVergiBilgisi() {
        return vergiBilgisi;
    }

    /**
     * Sets the value of the vergiBilgisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaturaType.VergiBilgisi }
     *     
     */
    public void setVergiBilgisi(FaturaType.VergiBilgisi value) {
        this.vergiBilgisi = value;
    }

    /**
     * Gets the value of the aliciBilgileri property.
     * 
     * @return
     *     possible object is
     *     {@link AliciType }
     *     
     */
    public AliciType getAliciBilgileri() {
        return aliciBilgileri;
    }

    /**
     * Sets the value of the aliciBilgileri property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliciType }
     *     
     */
    public void setAliciBilgileri(AliciType value) {
        this.aliciBilgileri = value;
    }

    /**
     * Gets the value of the internetSatisBilgi property.
     * 
     * @return
     *     possible object is
     *     {@link FaturaType.InternetSatisBilgi }
     *     
     */
    public FaturaType.InternetSatisBilgi getInternetSatisBilgi() {
        return internetSatisBilgi;
    }

    /**
     * Sets the value of the internetSatisBilgi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaturaType.InternetSatisBilgi }
     *     
     */
    public void setInternetSatisBilgi(FaturaType.InternetSatisBilgi value) {
        this.internetSatisBilgi = value;
    }

    /**
     * Gets the value of the ynOkcFisBilgisi property.
     * 
     * @return
     *     possible object is
     *     {@link FaturaType.YnOkcFisBilgisi }
     *     
     */
    public FaturaType.YnOkcFisBilgisi getYnOkcFisBilgisi() {
        return ynOkcFisBilgisi;
    }

    /**
     * Sets the value of the ynOkcFisBilgisi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaturaType.YnOkcFisBilgisi }
     *     
     */
    public void setYnOkcFisBilgisi(FaturaType.YnOkcFisBilgisi value) {
        this.ynOkcFisBilgisi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="webAdresi"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="odemeSekli" type="{http://earsiv.efatura.gov.tr}odemeTip"/&gt;
     *         &lt;element name="odemeAracisiAdi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="odemeTarihi" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="gonderiBilgileri" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="gonderimTarihi" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="gonderiTasiyan" type="{http://earsiv.efatura.gov.tr}kisiType"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "webAdresi",
        "odemeSekli",
        "odemeAracisiAdi",
        "odemeTarihi",
        "gonderiBilgileri"
    })
    public static class InternetSatisBilgi {

        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected String webAdresi;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String odemeSekli;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
        protected String odemeAracisiAdi;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar odemeTarihi;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
        protected FaturaType.InternetSatisBilgi.GonderiBilgileri gonderiBilgileri;

        /**
         * Gets the value of the webAdresi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebAdresi() {
            return webAdresi;
        }

        /**
         * Sets the value of the webAdresi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebAdresi(String value) {
            this.webAdresi = value;
        }

        /**
         * Gets the value of the odemeSekli property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOdemeSekli() {
            return odemeSekli;
        }

        /**
         * Sets the value of the odemeSekli property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOdemeSekli(String value) {
            this.odemeSekli = value;
        }

        /**
         * Gets the value of the odemeAracisiAdi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOdemeAracisiAdi() {
            return odemeAracisiAdi;
        }

        /**
         * Sets the value of the odemeAracisiAdi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOdemeAracisiAdi(String value) {
            this.odemeAracisiAdi = value;
        }

        /**
         * Gets the value of the odemeTarihi property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOdemeTarihi() {
            return odemeTarihi;
        }

        /**
         * Sets the value of the odemeTarihi property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOdemeTarihi(XMLGregorianCalendar value) {
            this.odemeTarihi = value;
        }

        /**
         * Gets the value of the gonderiBilgileri property.
         * 
         * @return
         *     possible object is
         *     {@link FaturaType.InternetSatisBilgi.GonderiBilgileri }
         *     
         */
        public FaturaType.InternetSatisBilgi.GonderiBilgileri getGonderiBilgileri() {
            return gonderiBilgileri;
        }

        /**
         * Sets the value of the gonderiBilgileri property.
         * 
         * @param value
         *     allowed object is
         *     {@link FaturaType.InternetSatisBilgi.GonderiBilgileri }
         *     
         */
        public void setGonderiBilgileri(FaturaType.InternetSatisBilgi.GonderiBilgileri value) {
            this.gonderiBilgileri = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="gonderimTarihi" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="gonderiTasiyan" type="{http://earsiv.efatura.gov.tr}kisiType"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "gonderimTarihi",
            "gonderiTasiyan"
        })
        public static class GonderiBilgileri {

            @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar gonderimTarihi;
            @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
            protected KisiType gonderiTasiyan;

            /**
             * Gets the value of the gonderimTarihi property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGonderimTarihi() {
                return gonderimTarihi;
            }

            /**
             * Sets the value of the gonderimTarihi property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGonderimTarihi(XMLGregorianCalendar value) {
                this.gonderimTarihi = value;
            }

            /**
             * Gets the value of the gonderiTasiyan property.
             * 
             * @return
             *     possible object is
             *     {@link KisiType }
             *     
             */
            public KisiType getGonderiTasiyan() {
                return gonderiTasiyan;
            }

            /**
             * Sets the value of the gonderiTasiyan property.
             * 
             * @param value
             *     allowed object is
             *     {@link KisiType }
             *     
             */
            public void setGonderiTasiyan(KisiType value) {
                this.gonderiTasiyan = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="vergilerToplami"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *               &lt;totalDigits value="18"/&gt;
     *               &lt;fractionDigits value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="vergi" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="matrah"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *                         &lt;totalDigits value="18"/&gt;
     *                         &lt;fractionDigits value="2"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="vergiKodu"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="0003"/&gt;
     *                         &lt;enumeration value="0015"/&gt;
     *                         &lt;enumeration value="0061"/&gt;
     *                         &lt;enumeration value="0071"/&gt;
     *                         &lt;enumeration value="0073"/&gt;
     *                         &lt;enumeration value="0074"/&gt;
     *                         &lt;enumeration value="0075"/&gt;
     *                         &lt;enumeration value="0076"/&gt;
     *                         &lt;enumeration value="0077"/&gt;
     *                         &lt;enumeration value="1047"/&gt;
     *                         &lt;enumeration value="1048"/&gt;
     *                         &lt;enumeration value="4080"/&gt;
     *                         &lt;enumeration value="4081"/&gt;
     *                         &lt;enumeration value="4171"/&gt;
     *                         &lt;enumeration value="9015"/&gt;
     *                         &lt;enumeration value="9021"/&gt;
     *                         &lt;enumeration value="9077"/&gt;
     *                         &lt;enumeration value="8001"/&gt;
     *                         &lt;enumeration value="8002"/&gt;
     *                         &lt;enumeration value="8003"/&gt;
     *                         &lt;enumeration value="8004"/&gt;
     *                         &lt;enumeration value="8005"/&gt;
     *                         &lt;enumeration value="8006"/&gt;
     *                         &lt;enumeration value="8007"/&gt;
     *                         &lt;enumeration value="8008"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="vergiTutari"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *                         &lt;totalDigits value="18"/&gt;
     *                         &lt;fractionDigits value="2"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="vergiOrani"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                         &lt;totalDigits value="3"/&gt;
     *                         &lt;maxInclusive value="100"/&gt;
     *                         &lt;minInclusive value="0"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="tevkifat" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="tevkifatKodu"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="301"/&gt;
     *                         &lt;enumeration value="302"/&gt;
     *                         &lt;enumeration value="303"/&gt;
     *                         &lt;enumeration value="304"/&gt;
     *                         &lt;enumeration value="305"/&gt;
     *                         &lt;enumeration value="306"/&gt;
     *                         &lt;enumeration value="308"/&gt;
     *                         &lt;enumeration value="309"/&gt;
     *                         &lt;enumeration value="310"/&gt;
     *                         &lt;enumeration value="311"/&gt;
     *                         &lt;enumeration value="312"/&gt;
     *                         &lt;enumeration value="313"/&gt;
     *                         &lt;enumeration value="314"/&gt;
     *                         &lt;enumeration value="315"/&gt;
     *                         &lt;enumeration value="316"/&gt;
     *                         &lt;enumeration value="317"/&gt;
     *                         &lt;enumeration value="318"/&gt;
     *                         &lt;enumeration value="319"/&gt;
     *                         &lt;enumeration value="320"/&gt;
     *                         &lt;enumeration value="321"/&gt;
     *                         &lt;enumeration value="350"/&gt;
     *                         &lt;enumeration value="601"/&gt;
     *                         &lt;enumeration value="602"/&gt;
     *                         &lt;enumeration value="603"/&gt;
     *                         &lt;enumeration value="604"/&gt;
     *                         &lt;enumeration value="605"/&gt;
     *                         &lt;enumeration value="606"/&gt;
     *                         &lt;enumeration value="607"/&gt;
     *                         &lt;enumeration value="608"/&gt;
     *                         &lt;enumeration value="609"/&gt;
     *                         &lt;enumeration value="610"/&gt;
     *                         &lt;enumeration value="611"/&gt;
     *                         &lt;enumeration value="612"/&gt;
     *                         &lt;enumeration value="613"/&gt;
     *                         &lt;enumeration value="614"/&gt;
     *                         &lt;enumeration value="615"/&gt;
     *                         &lt;enumeration value="616"/&gt;
     *                         &lt;enumeration value="617"/&gt;
     *                         &lt;enumeration value="618"/&gt;
     *                         &lt;enumeration value="619"/&gt;
     *                         &lt;enumeration value="620"/&gt;
     *                         &lt;enumeration value="621"/&gt;
     *                         &lt;enumeration value="622"/&gt;
     *                         &lt;enumeration value="623"/&gt;
     *                         &lt;enumeration value="650"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="tevkifatTutari"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *                         &lt;totalDigits value="18"/&gt;
     *                         &lt;fractionDigits value="2"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="tevkifatOrani"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
     *                         &lt;totalDigits value="5"/&gt;
     *                         &lt;fractionDigits value="2"/&gt;
     *                         &lt;maxInclusive value="100"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vergilerToplami",
        "vergi",
        "tevkifat"
    })
    public static class VergiBilgisi {

        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected BigDecimal vergilerToplami;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected List<FaturaType.VergiBilgisi.Vergi> vergi;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
        protected List<FaturaType.VergiBilgisi.Tevkifat> tevkifat;

        /**
         * Gets the value of the vergilerToplami property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getVergilerToplami() {
            return vergilerToplami;
        }

        /**
         * Sets the value of the vergilerToplami property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setVergilerToplami(BigDecimal value) {
            this.vergilerToplami = value;
        }

        /**
         * Gets the value of the vergi property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vergi property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVergi().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FaturaType.VergiBilgisi.Vergi }
         * 
         * 
         */
        public List<FaturaType.VergiBilgisi.Vergi> getVergi() {
            if (vergi == null) {
                vergi = new ArrayList<FaturaType.VergiBilgisi.Vergi>();
            }
            return this.vergi;
        }

        /**
         * Gets the value of the tevkifat property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tevkifat property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTevkifat().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FaturaType.VergiBilgisi.Tevkifat }
         * 
         * 
         */
        public List<FaturaType.VergiBilgisi.Tevkifat> getTevkifat() {
            if (tevkifat == null) {
                tevkifat = new ArrayList<FaturaType.VergiBilgisi.Tevkifat>();
            }
            return this.tevkifat;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="tevkifatKodu"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="301"/&gt;
         *               &lt;enumeration value="302"/&gt;
         *               &lt;enumeration value="303"/&gt;
         *               &lt;enumeration value="304"/&gt;
         *               &lt;enumeration value="305"/&gt;
         *               &lt;enumeration value="306"/&gt;
         *               &lt;enumeration value="308"/&gt;
         *               &lt;enumeration value="309"/&gt;
         *               &lt;enumeration value="310"/&gt;
         *               &lt;enumeration value="311"/&gt;
         *               &lt;enumeration value="312"/&gt;
         *               &lt;enumeration value="313"/&gt;
         *               &lt;enumeration value="314"/&gt;
         *               &lt;enumeration value="315"/&gt;
         *               &lt;enumeration value="316"/&gt;
         *               &lt;enumeration value="317"/&gt;
         *               &lt;enumeration value="318"/&gt;
         *               &lt;enumeration value="319"/&gt;
         *               &lt;enumeration value="320"/&gt;
         *               &lt;enumeration value="321"/&gt;
         *               &lt;enumeration value="350"/&gt;
         *               &lt;enumeration value="601"/&gt;
         *               &lt;enumeration value="602"/&gt;
         *               &lt;enumeration value="603"/&gt;
         *               &lt;enumeration value="604"/&gt;
         *               &lt;enumeration value="605"/&gt;
         *               &lt;enumeration value="606"/&gt;
         *               &lt;enumeration value="607"/&gt;
         *               &lt;enumeration value="608"/&gt;
         *               &lt;enumeration value="609"/&gt;
         *               &lt;enumeration value="610"/&gt;
         *               &lt;enumeration value="611"/&gt;
         *               &lt;enumeration value="612"/&gt;
         *               &lt;enumeration value="613"/&gt;
         *               &lt;enumeration value="614"/&gt;
         *               &lt;enumeration value="615"/&gt;
         *               &lt;enumeration value="616"/&gt;
         *               &lt;enumeration value="617"/&gt;
         *               &lt;enumeration value="618"/&gt;
         *               &lt;enumeration value="619"/&gt;
         *               &lt;enumeration value="620"/&gt;
         *               &lt;enumeration value="621"/&gt;
         *               &lt;enumeration value="622"/&gt;
         *               &lt;enumeration value="623"/&gt;
         *               &lt;enumeration value="650"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="tevkifatTutari"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
         *               &lt;totalDigits value="18"/&gt;
         *               &lt;fractionDigits value="2"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="tevkifatOrani"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
         *               &lt;totalDigits value="5"/&gt;
         *               &lt;fractionDigits value="2"/&gt;
         *               &lt;maxInclusive value="100"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tevkifatKodu",
            "tevkifatTutari",
            "tevkifatOrani"
        })
        public static class Tevkifat {

            @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
            protected String tevkifatKodu;
            @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
            protected BigDecimal tevkifatTutari;
            @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
            protected BigDecimal tevkifatOrani;

            /**
             * Gets the value of the tevkifatKodu property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTevkifatKodu() {
                return tevkifatKodu;
            }

            /**
             * Sets the value of the tevkifatKodu property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTevkifatKodu(String value) {
                this.tevkifatKodu = value;
            }

            /**
             * Gets the value of the tevkifatTutari property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTevkifatTutari() {
                return tevkifatTutari;
            }

            /**
             * Sets the value of the tevkifatTutari property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTevkifatTutari(BigDecimal value) {
                this.tevkifatTutari = value;
            }

            /**
             * Gets the value of the tevkifatOrani property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getTevkifatOrani() {
                return tevkifatOrani;
            }

            /**
             * Sets the value of the tevkifatOrani property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setTevkifatOrani(BigDecimal value) {
                this.tevkifatOrani = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="matrah"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
         *               &lt;totalDigits value="18"/&gt;
         *               &lt;fractionDigits value="2"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="vergiKodu"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="0003"/&gt;
         *               &lt;enumeration value="0015"/&gt;
         *               &lt;enumeration value="0061"/&gt;
         *               &lt;enumeration value="0071"/&gt;
         *               &lt;enumeration value="0073"/&gt;
         *               &lt;enumeration value="0074"/&gt;
         *               &lt;enumeration value="0075"/&gt;
         *               &lt;enumeration value="0076"/&gt;
         *               &lt;enumeration value="0077"/&gt;
         *               &lt;enumeration value="1047"/&gt;
         *               &lt;enumeration value="1048"/&gt;
         *               &lt;enumeration value="4080"/&gt;
         *               &lt;enumeration value="4081"/&gt;
         *               &lt;enumeration value="4171"/&gt;
         *               &lt;enumeration value="9015"/&gt;
         *               &lt;enumeration value="9021"/&gt;
         *               &lt;enumeration value="9077"/&gt;
         *               &lt;enumeration value="8001"/&gt;
         *               &lt;enumeration value="8002"/&gt;
         *               &lt;enumeration value="8003"/&gt;
         *               &lt;enumeration value="8004"/&gt;
         *               &lt;enumeration value="8005"/&gt;
         *               &lt;enumeration value="8006"/&gt;
         *               &lt;enumeration value="8007"/&gt;
         *               &lt;enumeration value="8008"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="vergiTutari"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
         *               &lt;totalDigits value="18"/&gt;
         *               &lt;fractionDigits value="2"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="vergiOrani"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *               &lt;totalDigits value="3"/&gt;
         *               &lt;maxInclusive value="100"/&gt;
         *               &lt;minInclusive value="0"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "matrah",
            "vergiKodu",
            "vergiTutari",
            "vergiOrani"
        })
        public static class Vergi {

            @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
            protected BigDecimal matrah;
            @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
            protected String vergiKodu;
            @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
            protected BigDecimal vergiTutari;
            @XmlElement(namespace = "http://earsiv.efatura.gov.tr")
            protected int vergiOrani;

            /**
             * Gets the value of the matrah property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getMatrah() {
                return matrah;
            }

            /**
             * Sets the value of the matrah property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setMatrah(BigDecimal value) {
                this.matrah = value;
            }

            /**
             * Gets the value of the vergiKodu property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVergiKodu() {
                return vergiKodu;
            }

            /**
             * Sets the value of the vergiKodu property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVergiKodu(String value) {
                this.vergiKodu = value;
            }

            /**
             * Gets the value of the vergiTutari property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getVergiTutari() {
                return vergiTutari;
            }

            /**
             * Sets the value of the vergiTutari property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setVergiTutari(BigDecimal value) {
                this.vergiTutari = value;
            }

            /**
             * Gets the value of the vergiOrani property.
             * 
             */
            public int getVergiOrani() {
                return vergiOrani;
            }

            /**
             * Sets the value of the vergiOrani property.
             * 
             */
            public void setVergiOrani(int value) {
                this.vergiOrani = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="okcSeriNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="zNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="fisNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="fisTarih" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "okcSeriNo",
        "zNo",
        "fisNo",
        "fisTarih"
    })
    public static class YnOkcFisBilgisi {

        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected String okcSeriNo;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected String zNo;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        protected String fisNo;
        @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fisTarih;

        /**
         * Gets the value of the okcSeriNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOkcSeriNo() {
            return okcSeriNo;
        }

        /**
         * Sets the value of the okcSeriNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOkcSeriNo(String value) {
            this.okcSeriNo = value;
        }

        /**
         * Gets the value of the zNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZNo() {
            return zNo;
        }

        /**
         * Sets the value of the zNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZNo(String value) {
            this.zNo = value;
        }

        /**
         * Gets the value of the fisNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFisNo() {
            return fisNo;
        }

        /**
         * Sets the value of the fisNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFisNo(String value) {
            this.fisNo = value;
        }

        /**
         * Gets the value of the fisTarih property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFisTarih() {
            return fisTarih;
        }

        /**
         * Sets the value of the fisTarih property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFisTarih(XMLGregorianCalendar value) {
            this.fisTarih = value;
        }

    }

}
