//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for faturaIptalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faturaIptalType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="faturaNo" type="{http://earsiv.efatura.gov.tr}idType"/&gt;
 *         &lt;element name="iptalTarihi" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="toplamTutar"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="18"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faturaIptalType", namespace = "http://earsiv.efatura.gov.tr", propOrder = {
    "faturaNo",
    "iptalTarihi",
    "toplamTutar"
})
public class FaturaIptalType {

    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected String faturaNo;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar iptalTarihi;
    @XmlElement(namespace = "http://earsiv.efatura.gov.tr", required = true)
    protected BigDecimal toplamTutar;

    /**
     * Gets the value of the faturaNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaturaNo() {
        return faturaNo;
    }

    /**
     * Sets the value of the faturaNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaturaNo(String value) {
        this.faturaNo = value;
    }

    /**
     * Gets the value of the iptalTarihi property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIptalTarihi() {
        return iptalTarihi;
    }

    /**
     * Sets the value of the iptalTarihi property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIptalTarihi(XMLGregorianCalendar value) {
        this.iptalTarihi = value;
    }

    /**
     * Gets the value of the toplamTutar property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getToplamTutar() {
        return toplamTutar;
    }

    /**
     * Sets the value of the toplamTutar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setToplamTutar(BigDecimal value) {
        this.toplamTutar = value;
    }

}
