//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Request related information context including data
 * 				such as TRANSACTION_ID, USER_ID etc.
 * 			
 * 
 * <p>Java class for REQUEST_HEADERType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REQUEST_HEADERType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SESSION_ID"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CLIENT_TXN_ID" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="64"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="INTL_TXN_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="INTL_PARENT_TXN_ID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ACTION_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="CHANGE_INFO" type="{http://schemas.i2i.com/ei/common}CHANGE_INFOType" minOccurs="0"/&gt;
 *         &lt;element name="REASON" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="64"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="APPLICATION_NAME" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="64"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HOSTNAME" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;maxLength value="64"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CHANNEL_NAME" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="64"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SIMULATION_FLAG" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="COMPRESSED" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="SIGN_STATUS" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="SIGNED"/&gt;
 *               &lt;enumeration value="SIGN_BY_CLIENTCER_TIFICATE"/&gt;
 *               &lt;enumeration value="SIGN_BY_ENTEGRATOR_CERTIFICATE"/&gt;
 *               &lt;enumeration value="NOSIGN"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ATTRIBUTES" type="{http://schemas.i2i.com/ei/common}ATTRIBUTESTYPE" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REQUEST_HEADERType", namespace = "http://schemas.i2i.com/ei/entity", propOrder = {
    "sessionid",
    "clienttxnid",
    "intltxnid",
    "intlparenttxnid",
    "actiondate",
    "changeinfo",
    "reason",
    "applicationname",
    "hostname",
    "channelname",
    "simulationflag",
    "compressed",
    "signstatus",
    "attributes"
})
public class REQUESTHEADERType {

    @XmlElement(name = "SESSION_ID", required = true)
    protected String sessionid;
    @XmlElement(name = "CLIENT_TXN_ID")
    protected String clienttxnid;
    @XmlElement(name = "INTL_TXN_ID")
    protected Long intltxnid;
    @XmlElement(name = "INTL_PARENT_TXN_ID")
    protected Long intlparenttxnid;
    @XmlElement(name = "ACTION_DATE")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actiondate;
    @XmlElement(name = "CHANGE_INFO")
    protected CHANGEINFOType changeinfo;
    @XmlElement(name = "REASON")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reason;
    @XmlElement(name = "APPLICATION_NAME")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String applicationname;
    @XmlElement(name = "HOSTNAME")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hostname;
    @XmlElement(name = "CHANNEL_NAME")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String channelname;
    @XmlElement(name = "SIMULATION_FLAG")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String simulationflag;
    @XmlElement(name = "COMPRESSED")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String compressed;
    @XmlElement(name = "SIGN_STATUS", defaultValue = "SIGNED")
    protected String signstatus;
    @XmlElement(name = "ATTRIBUTES")
    protected List<ATTRIBUTESTYPE> attributes;

    /**
     * Gets the value of the sessionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSESSIONID() {
        return sessionid;
    }

    /**
     * Sets the value of the sessionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSESSIONID(String value) {
        this.sessionid = value;
    }

    /**
     * Gets the value of the clienttxnid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLIENTTXNID() {
        return clienttxnid;
    }

    /**
     * Sets the value of the clienttxnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLIENTTXNID(String value) {
        this.clienttxnid = value;
    }

    /**
     * Gets the value of the intltxnid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getINTLTXNID() {
        return intltxnid;
    }

    /**
     * Sets the value of the intltxnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setINTLTXNID(Long value) {
        this.intltxnid = value;
    }

    /**
     * Gets the value of the intlparenttxnid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getINTLPARENTTXNID() {
        return intlparenttxnid;
    }

    /**
     * Sets the value of the intlparenttxnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setINTLPARENTTXNID(Long value) {
        this.intlparenttxnid = value;
    }

    /**
     * Gets the value of the actiondate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getACTIONDATE() {
        return actiondate;
    }

    /**
     * Sets the value of the actiondate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setACTIONDATE(XMLGregorianCalendar value) {
        this.actiondate = value;
    }

    /**
     * Gets the value of the changeinfo property.
     * 
     * @return
     *     possible object is
     *     {@link CHANGEINFOType }
     *     
     */
    public CHANGEINFOType getCHANGEINFO() {
        return changeinfo;
    }

    /**
     * Sets the value of the changeinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHANGEINFOType }
     *     
     */
    public void setCHANGEINFO(CHANGEINFOType value) {
        this.changeinfo = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREASON() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREASON(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the applicationname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLICATIONNAME() {
        return applicationname;
    }

    /**
     * Sets the value of the applicationname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLICATIONNAME(String value) {
        this.applicationname = value;
    }

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOSTNAME() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOSTNAME(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the channelname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHANNELNAME() {
        return channelname;
    }

    /**
     * Sets the value of the channelname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHANNELNAME(String value) {
        this.channelname = value;
    }

    /**
     * Gets the value of the simulationflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIMULATIONFLAG() {
        return simulationflag;
    }

    /**
     * Sets the value of the simulationflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIMULATIONFLAG(String value) {
        this.simulationflag = value;
    }

    /**
     * Gets the value of the compressed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPRESSED() {
        return compressed;
    }

    /**
     * Sets the value of the compressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPRESSED(String value) {
        this.compressed = value;
    }

    /**
     * Gets the value of the signstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIGNSTATUS() {
        return signstatus;
    }

    /**
     * Sets the value of the signstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIGNSTATUS(String value) {
        this.signstatus = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getATTRIBUTES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ATTRIBUTESTYPE }
     * 
     * 
     */
    public List<ATTRIBUTESTYPE> getATTRIBUTES() {
        if (attributes == null) {
            attributes = new ArrayList<ATTRIBUTESTYPE>();
        }
        return this.attributes;
    }

}
