//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:10 AM EET 
//


package com.izibiz.archive.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This will be fault type
 * 
 * <p>Java class for REQUEST_ERRORType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REQUEST_ERRORType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="INTL_TXN_ID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="TXN_ID" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="64"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ERROR_CODE"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="-99999"/&gt;
 *               &lt;maxInclusive value="99999"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ERROR_SHORT_DES"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ERROR_LONG_DES" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="STACKTRACE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ERROR_ELEMENT_INDEX" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REQUEST_ERRORType", namespace = "http://schemas.i2i.com/ei/entity", propOrder = {
    "intltxnid",
    "txnid",
    "errorcode",
    "errorshortdes",
    "errorlongdes",
    "stacktrace",
    "errorelementindex"
})
public class REQUESTERRORType {

    @XmlElement(name = "INTL_TXN_ID")
    protected long intltxnid;
    @XmlElement(name = "TXN_ID")
    protected String txnid;
    @XmlElement(name = "ERROR_CODE")
    protected int errorcode;
    @XmlElement(name = "ERROR_SHORT_DES", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String errorshortdes;
    @XmlElement(name = "ERROR_LONG_DES")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String errorlongdes;
    @XmlElement(name = "STACKTRACE")
    protected String stacktrace;
    @XmlElement(name = "ERROR_ELEMENT_INDEX")
    protected Integer errorelementindex;

    /**
     * Gets the value of the intltxnid property.
     * 
     */
    public long getINTLTXNID() {
        return intltxnid;
    }

    /**
     * Sets the value of the intltxnid property.
     * 
     */
    public void setINTLTXNID(long value) {
        this.intltxnid = value;
    }

    /**
     * Gets the value of the txnid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTXNID() {
        return txnid;
    }

    /**
     * Sets the value of the txnid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTXNID(String value) {
        this.txnid = value;
    }

    /**
     * Gets the value of the errorcode property.
     * 
     */
    public int getERRORCODE() {
        return errorcode;
    }

    /**
     * Sets the value of the errorcode property.
     * 
     */
    public void setERRORCODE(int value) {
        this.errorcode = value;
    }

    /**
     * Gets the value of the errorshortdes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORSHORTDES() {
        return errorshortdes;
    }

    /**
     * Sets the value of the errorshortdes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORSHORTDES(String value) {
        this.errorshortdes = value;
    }

    /**
     * Gets the value of the errorlongdes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORLONGDES() {
        return errorlongdes;
    }

    /**
     * Sets the value of the errorlongdes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORLONGDES(String value) {
        this.errorlongdes = value;
    }

    /**
     * Gets the value of the stacktrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTACKTRACE() {
        return stacktrace;
    }

    /**
     * Sets the value of the stacktrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTACKTRACE(String value) {
        this.stacktrace = value;
    }

    /**
     * Gets the value of the errorelementindex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getERRORELEMENTINDEX() {
        return errorelementindex;
    }

    /**
     * Sets the value of the errorelementindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setERRORELEMENTINDEX(Integer value) {
        this.errorelementindex = value;
    }

}
