//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:11 AM EET 
//


package com.izibiz.creditnote.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SendCreditNoteRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SendCreditNoteRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.i2i.com/ei/entity}REQUEST"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CREDITNOTE" type="{http://schemas.i2i.com/ei/wsdl}CREDITNOTE" maxOccurs="unbounded"/&gt;
 *         &lt;element name="CREDITNOTE_PROPERTIES" type="{http://schemas.i2i.com/ei/wsdl}CREDITNOTE_PROPERTIES" minOccurs="0"/&gt;
 *         &lt;element name="SERIES_PROPERTIES" type="{http://schemas.i2i.com/ei/wsdl}SERIES_PROPERTIES" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SendCreditNoteRequest", propOrder = {
    "creditnote",
    "creditnoteproperties",
    "seriesproperties"
})
public class SendCreditNoteRequest
    extends REQUEST
{

    @XmlElement(name = "CREDITNOTE", required = true)
    protected List<CREDITNOTE> creditnote;
    @XmlElement(name = "CREDITNOTE_PROPERTIES")
    protected CREDITNOTEPROPERTIES creditnoteproperties;
    @XmlElement(name = "SERIES_PROPERTIES")
    protected SERIESPROPERTIES seriesproperties;

    /**
     * Gets the value of the creditnote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditnote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCREDITNOTE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CREDITNOTE }
     * 
     * 
     */
    public List<CREDITNOTE> getCREDITNOTE() {
        if (creditnote == null) {
            creditnote = new ArrayList<CREDITNOTE>();
        }
        return this.creditnote;
    }

    /**
     * Gets the value of the creditnoteproperties property.
     * 
     * @return
     *     possible object is
     *     {@link CREDITNOTEPROPERTIES }
     *     
     */
    public CREDITNOTEPROPERTIES getCREDITNOTEPROPERTIES() {
        return creditnoteproperties;
    }

    /**
     * Sets the value of the creditnoteproperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CREDITNOTEPROPERTIES }
     *     
     */
    public void setCREDITNOTEPROPERTIES(CREDITNOTEPROPERTIES value) {
        this.creditnoteproperties = value;
    }

    /**
     * Gets the value of the seriesproperties property.
     * 
     * @return
     *     possible object is
     *     {@link SERIESPROPERTIES }
     *     
     */
    public SERIESPROPERTIES getSERIESPROPERTIES() {
        return seriesproperties;
    }

    /**
     * Sets the value of the seriesproperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SERIESPROPERTIES }
     *     
     */
    public void setSERIESPROPERTIES(SERIESPROPERTIES value) {
        this.seriesproperties = value;
    }

}
