//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:12 AM EET 
//


package com.izibiz.mutabakat.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Holds Comment Set Info
 * 
 * <p>Java class for COMMENTSETType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COMMENTSETType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.i2i.com/ei/common}ENTITYBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="COMMENT_SET_ID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="COMMENT" type="{http://schemas.i2i.com/ei/common}COMMENTType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMMENTSETType", propOrder = {
    "commentsetid",
    "comment"
})
public class COMMENTSETType
    extends ENTITYBaseType
{

    @XmlElement(name = "COMMENT_SET_ID")
    protected long commentsetid;
    @XmlElement(name = "COMMENT")
    protected List<COMMENTType> comment;

    /**
     * Gets the value of the commentsetid property.
     * 
     */
    public long getCOMMENTSETID() {
        return commentsetid;
    }

    /**
     * Sets the value of the commentsetid property.
     * 
     */
    public void setCOMMENTSETID(long value) {
        this.commentsetid = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOMMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COMMENTType }
     * 
     * 
     */
    public List<COMMENTType> getCOMMENT() {
        if (comment == null) {
            comment = new ArrayList<COMMENTType>();
        }
        return this.comment;
    }

}
