//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:12 AM EET 
//


package com.izibiz.mutabakat.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Helper Entity; defines basic properties for a
 * 				business entity
 * 			
 * 
 * <p>Java class for ENTITYType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ENTITYType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.i2i.com/ei/common}ENTITYBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FILESET" type="{http://schemas.i2i.com/ei/common}FILESETType" minOccurs="0"/&gt;
 *         &lt;element name="COMMENTSET" type="{http://schemas.i2i.com/ei/common}COMMENTSETType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ENTITYType", propOrder = {
    "fileset",
    "commentset"
})
public class ENTITYType
    extends ENTITYBaseType
{

    @XmlElement(name = "FILESET")
    protected FILESETType fileset;
    @XmlElement(name = "COMMENTSET")
    protected COMMENTSETType commentset;

    /**
     * Gets the value of the fileset property.
     * 
     * @return
     *     possible object is
     *     {@link FILESETType }
     *     
     */
    public FILESETType getFILESET() {
        return fileset;
    }

    /**
     * Sets the value of the fileset property.
     * 
     * @param value
     *     allowed object is
     *     {@link FILESETType }
     *     
     */
    public void setFILESET(FILESETType value) {
        this.fileset = value;
    }

    /**
     * Gets the value of the commentset property.
     * 
     * @return
     *     possible object is
     *     {@link COMMENTSETType }
     *     
     */
    public COMMENTSETType getCOMMENTSET() {
        return commentset;
    }

    /**
     * Sets the value of the commentset property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMMENTSETType }
     *     
     */
    public void setCOMMENTSET(COMMENTSETType value) {
        this.commentset = value;
    }

}
