//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:06:12 AM EET 
//


package com.izibiz.mutabakat.ws;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SendReconciliationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SendReconciliationRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://schemas.i2i.com/ei/entity}REQUEST"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RECONCILIATION" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TYPE" type="{http://schemas.izibiz.com/ei/wsdl/reconciliation}RECONCILIATION_TYPE"/&gt;
 *                   &lt;element name="UUID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="CUSTOMER_IDENTIFIER" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *                   &lt;element name="COMMERCIAL_NAME" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *                   &lt;element name="TAX_OFFICE" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *                   &lt;element name="CUSTOMER_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TELEPHONE_NO" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *                   &lt;element name="FAX_NO" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *                   &lt;element name="EMAIL" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *                   &lt;element name="CURRENCY_CODE" type="{http://schemas.izibiz.com/ei/wsdl/reconciliation}CURRENCY_CODE"/&gt;
 *                   &lt;element name="BABS_ACCOUNTING_PERIOD" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *                   &lt;element name="BA_DOCUMENT_COUNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="BA_DOCUMENT_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="BS_DOCUMENT_COUNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                   &lt;element name="BS_DOCUMENT_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="CM_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CM_AMOUNT_TYPE" type="{http://schemas.izibiz.com/ei/wsdl/reconciliation}CM_TYPE" minOccurs="0"/&gt;
 *                   &lt;element name="CM_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="NOTE" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SendReconciliationRequest", namespace = "http://schemas.izibiz.com/ei/wsdl/reconciliation", propOrder = {
    "reconciliation"
})
public class SendReconciliationRequest
    extends REQUEST
{

    @XmlElement(name = "RECONCILIATION", required = true)
    protected List<SendReconciliationRequest.RECONCILIATION> reconciliation;

    /**
     * Gets the value of the reconciliation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reconciliation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRECONCILIATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SendReconciliationRequest.RECONCILIATION }
     * 
     * 
     */
    public List<SendReconciliationRequest.RECONCILIATION> getRECONCILIATION() {
        if (reconciliation == null) {
            reconciliation = new ArrayList<SendReconciliationRequest.RECONCILIATION>();
        }
        return this.reconciliation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TYPE" type="{http://schemas.izibiz.com/ei/wsdl/reconciliation}RECONCILIATION_TYPE"/&gt;
     *         &lt;element name="UUID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="CUSTOMER_IDENTIFIER" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
     *         &lt;element name="COMMERCIAL_NAME" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
     *         &lt;element name="TAX_OFFICE" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
     *         &lt;element name="CUSTOMER_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TELEPHONE_NO" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
     *         &lt;element name="FAX_NO" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
     *         &lt;element name="EMAIL" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
     *         &lt;element name="CURRENCY_CODE" type="{http://schemas.izibiz.com/ei/wsdl/reconciliation}CURRENCY_CODE"/&gt;
     *         &lt;element name="BABS_ACCOUNTING_PERIOD" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
     *         &lt;element name="BA_DOCUMENT_COUNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="BA_DOCUMENT_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="BS_DOCUMENT_COUNT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *         &lt;element name="BS_DOCUMENT_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="CM_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CM_AMOUNT_TYPE" type="{http://schemas.izibiz.com/ei/wsdl/reconciliation}CM_TYPE" minOccurs="0"/&gt;
     *         &lt;element name="CM_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="NOTE" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "uuid",
        "customeridentifier",
        "commercialname",
        "taxoffice",
        "customeraddress",
        "telephoneno",
        "faxno",
        "email",
        "currencycode",
        "babsaccountingperiod",
        "badocumentcount",
        "badocumentamount",
        "bsdocumentcount",
        "bsdocumentamount",
        "cmdate",
        "cmamounttype",
        "cmamount",
        "note"
    })
    public static class RECONCILIATION {

        @XmlElement(name = "TYPE", required = true)
        @XmlSchemaType(name = "string")
        protected RECONCILIATIONTYPE type;
        @XmlElement(name = "UUID", required = true)
        protected String uuid;
        @XmlElement(name = "CUSTOMER_IDENTIFIER", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String customeridentifier;
        @XmlElement(name = "COMMERCIAL_NAME", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String commercialname;
        @XmlElement(name = "TAX_OFFICE")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String taxoffice;
        @XmlElement(name = "CUSTOMER_ADDRESS", required = true)
        protected String customeraddress;
        @XmlElement(name = "TELEPHONE_NO")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String telephoneno;
        @XmlElement(name = "FAX_NO")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String faxno;
        @XmlElement(name = "EMAIL", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String email;
        @XmlElement(name = "CURRENCY_CODE", required = true)
        @XmlSchemaType(name = "string")
        protected CURRENCYCODE currencycode;
        @XmlElement(name = "BABS_ACCOUNTING_PERIOD")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String babsaccountingperiod;
        @XmlElement(name = "BA_DOCUMENT_COUNT")
        protected Integer badocumentcount;
        @XmlElement(name = "BA_DOCUMENT_AMOUNT")
        protected BigDecimal badocumentamount;
        @XmlElement(name = "BS_DOCUMENT_COUNT")
        protected Integer bsdocumentcount;
        @XmlElement(name = "BS_DOCUMENT_AMOUNT")
        protected BigDecimal bsdocumentamount;
        @XmlElement(name = "CM_DATE")
        protected String cmdate;
        @XmlElement(name = "CM_AMOUNT_TYPE")
        @XmlSchemaType(name = "string")
        protected CMTYPE cmamounttype;
        @XmlElement(name = "CM_AMOUNT")
        protected BigDecimal cmamount;
        @XmlElement(name = "NOTE")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String note;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link RECONCILIATIONTYPE }
         *     
         */
        public RECONCILIATIONTYPE getTYPE() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link RECONCILIATIONTYPE }
         *     
         */
        public void setTYPE(RECONCILIATIONTYPE value) {
            this.type = value;
        }

        /**
         * Gets the value of the uuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUUID() {
            return uuid;
        }

        /**
         * Sets the value of the uuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUUID(String value) {
            this.uuid = value;
        }

        /**
         * Gets the value of the customeridentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCUSTOMERIDENTIFIER() {
            return customeridentifier;
        }

        /**
         * Sets the value of the customeridentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCUSTOMERIDENTIFIER(String value) {
            this.customeridentifier = value;
        }

        /**
         * Gets the value of the commercialname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCOMMERCIALNAME() {
            return commercialname;
        }

        /**
         * Sets the value of the commercialname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCOMMERCIALNAME(String value) {
            this.commercialname = value;
        }

        /**
         * Gets the value of the taxoffice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTAXOFFICE() {
            return taxoffice;
        }

        /**
         * Sets the value of the taxoffice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTAXOFFICE(String value) {
            this.taxoffice = value;
        }

        /**
         * Gets the value of the customeraddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCUSTOMERADDRESS() {
            return customeraddress;
        }

        /**
         * Sets the value of the customeraddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCUSTOMERADDRESS(String value) {
            this.customeraddress = value;
        }

        /**
         * Gets the value of the telephoneno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTELEPHONENO() {
            return telephoneno;
        }

        /**
         * Sets the value of the telephoneno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTELEPHONENO(String value) {
            this.telephoneno = value;
        }

        /**
         * Gets the value of the faxno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFAXNO() {
            return faxno;
        }

        /**
         * Sets the value of the faxno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFAXNO(String value) {
            this.faxno = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMAIL() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMAIL(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the currencycode property.
         * 
         * @return
         *     possible object is
         *     {@link CURRENCYCODE }
         *     
         */
        public CURRENCYCODE getCURRENCYCODE() {
            return currencycode;
        }

        /**
         * Sets the value of the currencycode property.
         * 
         * @param value
         *     allowed object is
         *     {@link CURRENCYCODE }
         *     
         */
        public void setCURRENCYCODE(CURRENCYCODE value) {
            this.currencycode = value;
        }

        /**
         * Gets the value of the babsaccountingperiod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBABSACCOUNTINGPERIOD() {
            return babsaccountingperiod;
        }

        /**
         * Sets the value of the babsaccountingperiod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBABSACCOUNTINGPERIOD(String value) {
            this.babsaccountingperiod = value;
        }

        /**
         * Gets the value of the badocumentcount property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBADOCUMENTCOUNT() {
            return badocumentcount;
        }

        /**
         * Sets the value of the badocumentcount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBADOCUMENTCOUNT(Integer value) {
            this.badocumentcount = value;
        }

        /**
         * Gets the value of the badocumentamount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBADOCUMENTAMOUNT() {
            return badocumentamount;
        }

        /**
         * Sets the value of the badocumentamount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBADOCUMENTAMOUNT(BigDecimal value) {
            this.badocumentamount = value;
        }

        /**
         * Gets the value of the bsdocumentcount property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBSDOCUMENTCOUNT() {
            return bsdocumentcount;
        }

        /**
         * Sets the value of the bsdocumentcount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBSDOCUMENTCOUNT(Integer value) {
            this.bsdocumentcount = value;
        }

        /**
         * Gets the value of the bsdocumentamount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBSDOCUMENTAMOUNT() {
            return bsdocumentamount;
        }

        /**
         * Sets the value of the bsdocumentamount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBSDOCUMENTAMOUNT(BigDecimal value) {
            this.bsdocumentamount = value;
        }

        /**
         * Gets the value of the cmdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCMDATE() {
            return cmdate;
        }

        /**
         * Sets the value of the cmdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCMDATE(String value) {
            this.cmdate = value;
        }

        /**
         * Gets the value of the cmamounttype property.
         * 
         * @return
         *     possible object is
         *     {@link CMTYPE }
         *     
         */
        public CMTYPE getCMAMOUNTTYPE() {
            return cmamounttype;
        }

        /**
         * Sets the value of the cmamounttype property.
         * 
         * @param value
         *     allowed object is
         *     {@link CMTYPE }
         *     
         */
        public void setCMAMOUNTTYPE(CMTYPE value) {
            this.cmamounttype = value;
        }

        /**
         * Gets the value of the cmamount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCMAMOUNT() {
            return cmamount;
        }

        /**
         * Sets the value of the cmamount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCMAMOUNT(BigDecimal value) {
            this.cmamount = value;
        }

        /**
         * Gets the value of the note property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNOTE() {
            return note;
        }

        /**
         * Sets the value of the note property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNOTE(String value) {
            this.note = value;
        }

    }

}
